import {directedLink,evaluateTarget,routeBetween,type RadioNode,type Environment,type Surface,type Target,type TargetResult,type Budget} from './model';
export type Candidate={id:string;node:RadioNode;allowed:boolean;feasibility:'confirmed'|'unknown'|'excluded';reason:string;siteId?:string};
export type OptimizeRequest={nodes:RadioNode[];params:Environment;targets:Target[];candidates:Candidate[];budget:number;lockedIds?:string[];surface:Surface;cancelled?:()=>boolean};
export type Alternative={nodes:RadioNode[];candidateIds:string[];score:number;gain:number;targetsGained:string[];gaps:string[];unknown:string[];bottleneckDb:number};
export type OptimizeResult={method:string;baseline:Alternative;best:Alternative;alternatives:Alternative[];contributions:{id:string;scoreLoss:number}[];evaluations:number;cancelled:boolean;limitations:string[]};
export function optimizePlacement(req:OptimizeRequest):OptimizeResult{
 const {nodes,params,surface,targets}=req,budget=Math.max(0,Math.min(6,Math.floor(req.budget)));
 if(!Number.isFinite(budget)||targets.some(t=>!Number.isFinite(t.weight??1)||(t.weight??1)<0))throw new Error('Invalid budget or target weight');
 const candidates=req.candidates.filter(c=>c.node.kind!=='totem'&&c.allowed&&c.feasibility!=='excluded'&&!nodes.some(n=>n.id===c.node.id)).sort((a,b)=>a.id.localeCompare(b.id)).slice(0,64);
 const cache=new Map<string,Budget>();const link=(a:RadioNode,b:RadioNode)=>{const key=JSON.stringify([a,b]);let v=cache.get(key);if(!v){v=directedLink(a,b,params,surface);if(cache.size<50000)cache.set(key,v);}return v;};let evaluations=0;
 const evaluate=(chosen:Candidate[]):Alternative=>{evaluations++;const set=[...nodes,...chosen.map(c=>c.node)];const root=params.meshRootId??params.rootId??nodes.find(n=>n.kind!=='totem')?.id??'';const connected=chosen.every(c=>[routeBetween(set,c.node.id,root,params,surface,link),routeBetween(set,root,c.node.id,params,surface,link)].every(r=>r.status==='likely'||r.status==='marginal'));const results:TargetResult[]=targets.map(t=>evaluateTarget(t,set,params,surface,'mesh',link));const reached=results.filter(r=>r.status==='likely'||r.status==='marginal');return {nodes:set,candidateIds:chosen.map(c=>c.id),score:connected?reached.reduce((a,r)=>a+(r.target.weight??1),0):-Infinity,gain:0,targetsGained:reached.map(r=>r.target.id),gaps:results.filter(r=>r.status==='unavailable').map(r=>r.target.id),unknown:results.filter(r=>r.status==='unknown').map(r=>r.target.id),bottleneckDb:reached.length?Math.min(...reached.map(r=>r.marginDb)):-Infinity};};
 const baseline=evaluate([]);let best=baseline,chosen:Candidate[]=[];const alternatives:Alternative[]=[];
 const better=(a:Alternative,b:Alternative)=>a.score>b.score||(a.score===b.score&&(a.candidateIds.length<b.candidateIds.length||(a.candidateIds.length===b.candidateIds.length&&a.bottleneckDb>b.bottleneckDb)));
 const feasible=(c:Candidate,set:Candidate[])=>!set.some(v=>v.id===c.id||(v.siteId??v.id)===(c.siteId??c.id))&&!nodes.some(n=>n.x===c.node.x&&n.y===c.node.y);
 for(let k=0;k<budget&&!req.cancelled?.();k++){let pick:Candidate|undefined,nextBest=best;for(const c of candidates){if(req.cancelled?.())break;if(!feasible(c,chosen))continue;const r=evaluate([...chosen,c]);alternatives.push(r);if(better(r,nextBest)){nextBest=r;pick=c;}}if(!pick)break;chosen=[...chosen,pick];best=nextBest;}
 // One deterministic local-swap pass; baseline is immutable and never worsens.
 for(let i=0;i<chosen.length&&!req.cancelled?.();i++){const original=chosen[i];if(req.lockedIds?.includes(original.node.id))continue;for(const c of candidates){if(req.cancelled?.())break;const rest=chosen.filter((_,j)=>j!==i);if(!feasible(c,rest))continue;const trial=[...rest,c],r=evaluate(trial);alternatives.push(r);if(better(r,best)){chosen=trial;best=r;break;}}}
 const decorate=(r:Alternative):Alternative=>({...r,gain:r.score-baseline.score,targetsGained:r.targetsGained.filter(id=>!baseline.targetsGained.includes(id))});
 const contributions=chosen.map(c=>({id:c.node.id,scoreLoss:best.score-evaluate(chosen.filter(v=>v.id!==c.id)).score}));
 const seen=new Set<string>();const ranked=alternatives.filter(r=>r.score>=baseline.score).sort((a,b)=>b.score-a.score||a.candidateIds.length-b.candidateIds.length||b.bottleneckDb-a.bottleneckDb).filter(r=>{const key=[...r.candidateIds].sort().join('|');if(seen.has(key))return false;seen.add(key);return true;}).slice(0,3).map(decorate);
 return {method:'Deterministic greedy plus one local-swap pass; best found, not global optimum',baseline,best:decorate(best),alternatives:ranked,contributions,evaluations,cancelled:req.cancelled?.()??false,limitations:['Maximum 64 candidates and six added devices.','Existing nodes are fixed; excluded sites never selected; unknown installation feasibility requires site verification.','Objective is weighted bidirectional mesh target reachability; identical targets and RF engine used for baseline and recommendations.','Single-add greedy may miss a beneficial multi-relay chain; alternatives are searched layouts, not proof of optimality.','Unknown terrain/hardware never scores as served.','Results require field validation; installation access, power and mounting are user supplied constraints.']};
}
export function gridCandidates(surface:Surface,spacing=25,heights=[3,6]):Candidate[]{const out:Candidate[]=[];for(let y=spacing/2;y<surface.rows;y+=spacing)for(let x=spacing/2;x<surface.cols;x+=spacing){if(!Number.isFinite(surface.elevation(x,y)))continue;for(const agl of heights)out.push({id:`candidate-${x}-${y}-${agl}`,siteId:`${x}:${y}`,node:{id:`relay-${x}-${y}-${agl}`,kind:'v4',x,y,agl,role:'router',label:`Candidate ${x}, ${y} / ${agl} m`},allowed:true,feasibility:'unknown',reason:'Access, property permission, power and mount unverified.'});}return out;}
