import { parseScenario } from './store';
import { createStarterScenario, samePlan } from './starter-plan';
import { STARTER_PARAMS } from './placement-policy';
import { suggestClients, MODEL_VERSION } from './radio';
import { TERRAIN_VERSION } from './terrain';

export const SCENARIO_STORAGE='ridgemesh-scenario-v2';
export const BACKUP_STORAGE='ridgemesh-scenario-before-recommended';
export const REJECTED_STORAGE='ridgemesh-scenario-unreadable-backup';
export function resolveStartup(saved:string|null){
 if(saved===null)return {scenario:createStarterScenario(),source:'recommended' as const};
 try{
  const scenario=parseScenario(saved,TERRAIN_VERSION,MODEL_VERSION);
  // Only the exact former autogenerated scaffold is upgraded; custom and empty plans are retained.
  if(scenario.name==='My event plan'&&samePlan({nodes:scenario.nodes,params:scenario.params},{nodes:suggestClients(),params:STARTER_PARAMS}))return {scenario:createStarterScenario(),source:'upgraded' as const,backup:saved};
  return {scenario,source:'saved' as const};
 }catch(error){return {scenario:createStarterScenario(),source:'recovered' as const,rejected:saved,error:error instanceof Error?error.message:'Saved plan could not be read.'};}
}
