import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { COLS, ROWS, CELL_M, HEIGHT, ELEV_MIN, elevBilinear, contourSegs, gridToLl } from './terrain';
import { KIND_META, isFixed, isRouter, ROLE_LABELS, targetPolygons, type Heat, type Node, type SimParams, type Status } from './radio';
import { SITE_AREAS, SITE_PATHS, SITE_POINTS } from './site-features';
import { coverageColor } from './coverage-view';
import { scenePoint, clipPolygonToRect, clipPolygonToTriangle, heatCellIndex, polygonArea, triangleSurfaceElevation, layoutSceneLabels, type GridPoint } from './scene-geometry';
export type ViewName='north'|'east'|'south'|'west'|'top';
export type SceneState={nodes:Node[];params:SimParams;heat:Heat|null;overlay:'mesh'|'none';imagery:string;view:ViewName;opacity:number;layers:{labels:boolean;heights:boolean;zones:boolean;routes:boolean;contours:boolean;coordinates:boolean};routeLines:Array<{a:{x:number;y:number;agl?:number;kind?:Node['kind']};b:{x:number;y:number;agl?:number;kind?:Node['kind']};status:Status}>;selectedId:string|null;focus:{x:number;y:number}|null;fitKey:number;onSelect:(id:string)=>void;onInspect:(p:{x:number;y:number;label?:string})=>void;onCursor?:(p:{x:number;y:number}|null)=>void};
export type ValleyApi={destroy:()=>void;update:(s:SceneState)=>void;zoom:(factor:number)=>void};
type Label={el:HTMLButtonElement;leader:SVGLineElement;point:THREE.Vector3;priority:number};
const routeColors:Record<Status,string>={likely:'#77c9ff',marginal:'#f2ba5b',unavailable:'#f47e76',unknown:'#bcc4cf'};
export function mountValley(host:HTMLElement,initial:SceneState):ValleyApi{
 const scene=new THREE.Scene();scene.background=new THREE.Color('#15202c');
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;
 renderer.domElement.setAttribute('aria-label','Actual-scale 3D terrain and modeled coverage');host.appendChild(renderer.domElement);
 const leaderHost=document.createElementNS('http://www.w3.org/2000/svg','svg');leaderHost.setAttribute('aria-hidden','true');leaderHost.classList.add('three-label-leaders');Object.assign(leaderHost.style,{position:'absolute',inset:'0',width:'100%',height:'100%',pointerEvents:'none',overflow:'hidden'});host.appendChild(leaderHost);
 const labelHost=document.createElement('div');labelHost.className='three-labels';Object.assign(labelHost.style,{position:'absolute',inset:'0',pointerEvents:'none',overflow:'hidden'});host.appendChild(labelHost);
 const coordinate=document.createElement('div');coordinate.className='three-coordinates';Object.assign(coordinate.style,{position:'absolute',bottom:'36px',right:'12px',color:'#fff',background:'#122132e6',fontSize:'11px',padding:'4px 7px',pointerEvents:'none'});host.appendChild(coordinate);
 const camera=new THREE.PerspectiveCamera(43,1,.1,1500),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;controls.maxPolarAngle=Math.PI/2-.02;controls.minDistance=8;controls.maxDistance=550;
 const geometry=new THREE.BufferGeometry(),positions=new Float32Array(COLS*ROWS*3),uv=new Float32Array(COLS*ROWS*2),indices:number[]=[];
 const world=(x:number,y:number,agl=0)=>new THREE.Vector3(...scenePoint(x,y,elevBilinear(x,y),agl,COLS,ROWS,CELL_M,ELEV_MIN));
 for(let j=0;j<ROWS;j++)for(let i=0;i<COLS;i++){const k=j*COLS+i;positions.set(scenePoint(i,j,HEIGHT[k],0,COLS,ROWS,CELL_M,ELEV_MIN),3*k);uv[k*2]=i/(COLS-1);uv[k*2+1]=1-j/(ROWS-1);if(i<COLS-1&&j<ROWS-1)indices.push(k,k+COLS,k+1,k+1,k+COLS,k+COLS+1);}
 geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('uv',new THREE.BufferAttribute(uv,2));geometry.setIndex(indices);geometry.computeBoundingSphere();
 const material=new THREE.MeshBasicMaterial({color:'#ffffff',side:THREE.DoubleSide}),land=new THREE.Mesh(geometry,material);scene.add(land);
 const objects=new THREE.Group();scene.add(objects);let labels:Label[]=[],state=initial,alive=true,raf=0,imageKey='',loadId=0,lastView='',lastFit=-1,lastFocus='';
 let previousHeat:Heat|null|undefined,previousNodes:Node[]|undefined,previousOverlay='',previousLayerKey='',previousRoutes:SceneState['routeLines']|undefined,previousSelection:string|null|undefined,previousOpacity=-1,previousTarget='';
 const allPoints=SITE_AREAS.flatMap(a=>a.polygon),bounds={minX:Math.min(...allPoints.map(p=>p[0])),maxX:Math.max(...allPoints.map(p=>p[0])),minY:Math.min(...allPoints.map(p=>p[1])),maxY:Math.max(...allPoints.map(p=>p[1]))};
 const center={x:(bounds.minX+bounds.maxX)/2,y:(bounds.minY+bounds.maxY)/2};
 function positionLabels(){const r=host.getBoundingClientRect(),placed:Array<{x:number;y:number;w:number;h:number}>=[];const mobile=r.width<600;for(const label of labels){label.el.style.maxWidth=mobile?(label.priority===0?'194px':'112px'):(label.priority===0?'230px':'165px');label.el.style.fontSize=mobile?(label.priority===0?'10px':'9px'):(label.priority===0?'11px':'10px');label.el.style.padding=mobile?'3px 5px':label.priority===0?'5px 8px':'3px 6px';}const mobileLayout=mobile?layoutSceneLabels(labels.map(label=>{const p=label.point.clone().project(camera);return {anchorX:(p.x+1)*r.width/2,anchorY:(1-p.y)*r.height/2,w:label.el.offsetWidth,h:label.el.offsetHeight};}),{x:6,y:136,w:Math.max(1,r.width-12),h:Math.max(60,r.height-136-165)},[{x:0,y:140,w:48,h:115}]):null;for(const label of labels){const p=label.point.clone().project(camera);if(p.z>1||p.z< -1||Math.abs(p.x)>1.2||Math.abs(p.y)>1.2){label.el.style.visibility='hidden';label.leader.style.visibility='hidden';continue;}label.el.style.visibility='visible';label.leader.style.visibility='visible';const w=label.el.offsetWidth,h=label.el.offsetHeight;let x=Math.max(5,Math.min(r.width-w-5,(p.x+1)*r.width/2-w/2));let y=Math.max(8,Math.min(r.height-h-55,(1-p.y)*r.height/2-h-8));for(let attempt=0;!mobile&&attempt<14;attempt++){if(!placed.some(o=>x<o.x+o.w+5&&x+w+5>o.x&&y<o.y+o.h+4&&y+h+4>o.y))break;y=Math.max(8,Math.min(r.height-h-55,y+(attempt%2===0?-1:1)*(h+5)*(Math.floor(attempt/2)+1)));}if(mobileLayout){const placement=mobileLayout[labels.indexOf(label)];x=placement.x;y=placement.y;}label.el.style.transform=`translate(${x}px,${y}px)`;const anchorX=(p.x+1)*r.width/2,anchorY=(1-p.y)*r.height/2;label.leader.setAttribute('x1',String(anchorX));label.leader.setAttribute('y1',String(anchorY));label.leader.setAttribute('x2',String(Math.max(x,Math.min(x+w,anchorX))));label.leader.setAttribute('y2',String(Math.max(y,Math.min(y+h,anchorY))));placed.push({x,y,w,h});}}
 function render(){raf=0;if(!alive)return;renderer.render(scene,camera);positionLabels();renderer.domElement.dataset.geometries=String(renderer.info.memory.geometries);renderer.domElement.dataset.textures=String(renderer.info.memory.textures);}
 function requestRender(){if(alive&&!raf)raf=requestAnimationFrame(render);}
 controls.addEventListener('change',requestRender);
 function disposeObjects(){objects.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose());}});objects.clear();labels=[];labelHost.replaceChildren();leaderHost.replaceChildren();}
 function line(points:THREE.Vector3[],color:string,opacity=1){const geo=new THREE.BufferGeometry().setFromPoints(points),mat=new THREE.LineBasicMaterial({color,transparent:opacity<1,opacity,depthTest:true});objects.add(new THREE.Line(geo,mat));}
 function groundLine(points:GridPoint[],color:string,opacity=.85){const sampled:THREE.Vector3[]=[];for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1],steps=Math.max(1,Math.ceil(Math.hypot(b[0]-a[0],b[1]-a[1])));for(let j=0;j<steps;j++)sampled.push(world(a[0]+(b[0]-a[0])*j/steps,a[1]+(b[1]-a[1])*j/steps,.7));}if(points.length)sampled.push(world(...points.at(-1)!, .7));line(sampled,color,opacity);}
 function addLabel(text:string,p:THREE.Vector3,onClick:()=>void,node?:Node){const el=document.createElement('button');el.type='button';el.className=node?'three-node map-node':'three-place site-label';el.textContent=text;el.setAttribute('aria-label',node?`Select ${node.label}`:`Inspect ${text}`);Object.assign(el.style,{position:'absolute',left:'0',top:'0',pointerEvents:'auto',maxWidth:node?'230px':'165px',padding:node?'5px 8px':'3px 6px',border:`1px solid ${node?.id==='primary-p1'?'#ffd07b':node?'#95cdff':'#e5d6a2'}`,borderRadius:'6px',background:node?.id===state.selectedId?'#344e69f5':'#142334ed',color:node?'#f6fbff':'#fff0c7',fontSize:node?'11px':'10px',lineHeight:'1.35',textAlign:'left',cursor:'pointer',boxShadow:'0 1px 4px #0009'});if(node){el.dataset.nodeId=node.id;el.dataset.x=String(node.x);el.dataset.y=String(node.y);el.dataset.agl=String(node.agl??KIND_META[node.kind].agl);el.dataset.role=isRouter(node)?'router':isFixed(node)?'fixed-client':'handheld';}el.addEventListener('click',onClick);labelHost.appendChild(el);const leader=document.createElementNS('http://www.w3.org/2000/svg','line');leader.setAttribute('stroke',node?.id==='primary-p1'?'#ffd07b':node?'#95cdff':'#eee3bc');leader.setAttribute('stroke-width','1');leader.setAttribute('opacity','.8');leaderHost.appendChild(leader);labels.push({el,leader,point:p,priority:node?0:1});}
 function rebuild(){disposeObjects();let heatTriangles=0;const h=state.heat;
  if(h&&state.overlay!=='none'){
   const vertices:number[]=[],colors:number[]=[],polygons:GridPoint[][]=h.scope==='landscape'?[[[0,0],[COLS-1,0],[COLS-1,ROWS-1],[0,ROWS-1]]]:targetPolygons(state.params),triangles=polygons.flatMap(p=>THREE.ShapeUtils.triangulateShape(p.map(v=>new THREE.Vector2(...v)),[]).map(ids=>ids.map(i=>p[i]) as GridPoint[]));
   for(const triangle of triangles){const minX=Math.max(0,Math.floor(Math.min(...triangle.map(p=>p[0])))),maxX=Math.min(COLS-1,Math.ceil(Math.max(...triangle.map(p=>p[0])))),minY=Math.max(0,Math.floor(Math.min(...triangle.map(p=>p[1])))),maxY=Math.min(ROWS-1,Math.ceil(Math.max(...triangle.map(p=>p[1]))));
    for(let y=minY;y<maxY;y++)for(let x=minX;x<maxX;x++){const k=heatCellIndex(x+.5,y+.5,h.step,h.w,h.h);if(k===null||(h.scope!=='landscape'&&!h.targetWeights[k]))continue;const cell=clipPolygonToRect(triangle,x,y,x+1,y+1);if(cell.length<3||polygonArea(cell)<1e-8)continue;const color=new THREE.Color(coverageColor(h.mesh[k],h.meshMargin[k]));const terrainTriangles:[GridPoint,GridPoint,GridPoint][]=[[[x,y],[x+1,y],[x,y+1]],[[x+1,y],[x+1,y+1],[x,y+1]]];for(const terrainTriangle of terrainTriangles){const clipped=clipPolygonToTriangle(cell,terrainTriangle);if(clipped.length<3||polygonArea(clipped)<1e-8)continue;for(let i=1;i<clipped.length-1;i++){for(const p of [clipped[0],clipped[i],clipped[i+1]]){const ground=triangleSurfaceElevation(p[0],p[1],COLS,ROWS,(x,y)=>HEIGHT[y*COLS+x]);const v=scenePoint(p[0],p[1],ground,.35,COLS,ROWS,CELL_M,ELEV_MIN);vertices.push(...v);colors.push(color.r,color.g,color.b);}heatTriangles++;}}}
   }
   const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeBoundingSphere();objects.add(new THREE.Mesh(geo,new THREE.MeshBasicMaterial({vertexColors:true,transparent:true,opacity:state.opacity,depthWrite:false,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1})));
  }
  if(state.layers.zones){for(const area of SITE_AREAS)groundLine([...area.polygon,area.polygon[0]],'#ffedb0');for(const path of SITE_PATHS)groundLine(path.points,path.kind==='creek'?'#8ddaf5':'#fff6de');}
  if(state.layers.contours){const segments=contourSegs();for(const [values,opacity] of [[segments.minor,.25],[segments.major,.55]] as const){const points:THREE.Vector3[]=[];for(let i=0;i<values.length;i+=4)points.push(world(values[i],values[i+1],.6),world(values[i+2],values[i+3],.6));objects.add(new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:'#fff',transparent:true,opacity})));}}
  if(state.layers.routes)for(const r of state.routeLines){const route=new THREE.Line(new THREE.BufferGeometry().setFromPoints([world(r.a.x,r.a.y,r.a.agl??(r.a.kind?KIND_META[r.a.kind].agl:1.5)),world(r.b.x,r.b.y,r.b.agl??(r.b.kind?KIND_META[r.b.kind].agl:1.5))]),new THREE.LineDashedMaterial({color:routeColors[r.status],dashSize:.8,gapSize:.45,depthTest:false,depthWrite:false,transparent:true,opacity:.95}));route.computeLineDistances();route.renderOrder=3;objects.add(route);}
  for(const n of state.nodes){const agl=n.agl??KIND_META[n.kind].agl,p=world(n.x,n.y,agl),ground=world(n.x,n.y),height=agl/CELL_M,color=n.id==='primary-p1'?'#ffd07b':'#86c6ff';const pole=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,Math.max(height,.005),6),new THREE.MeshBasicMaterial({color}));pole.position.set(p.x,ground.y+height/2,p.z);objects.add(pole);
   // Symbolic marker radius is screen affordance; the pole endpoint remains actual AGL.
   const marker=new THREE.Mesh(new THREE.SphereGeometry(n.id==='primary-p1'?.32:.22,10,8),new THREE.MeshBasicMaterial({color}));marker.position.copy(p);objects.add(marker);
   const name=isRouter(n)?`R${state.nodes.filter(isRouter).indexOf(n)+1}`:isFixed(n)?`C${state.nodes.filter(v=>isFixed(v)&&!isRouter(v)).indexOf(n)+1}`:'H',site=SITE_POINTS.find(v=>Math.hypot(v.x-n.x,v.y-n.y)<2),text=`${name} · ${n.id==='primary-p1'?'P1 solar':ROLE_LABELS[n.role??'client']}${state.layers.labels?` · ${site?.label??n.label}`:''}${state.layers.heights?` · ${agl} m AGL`:''}`;addLabel(text,p,()=>state.onSelect(n.id),n);
  }
  if(state.layers.labels)for(const site of SITE_POINTS){if(state.nodes.some(n=>Math.hypot(n.x-site.x,n.y-site.y)<2))continue;addLabel(site.label,world(site.x,site.y,1),()=>state.onInspect({x:site.x,y:site.y,label:site.label}));}
  labels.sort((a,b)=>a.priority-b.priority);coordinate.style.display=state.layers.coordinates?'block':'none';coordinate.textContent=state.layers.coordinates?'Move over terrain for coordinates':'';
  Object.assign(renderer.domElement.dataset,{terrainScale:'1',heatScope:h?.scope??'event',routeStyle:'schematic-dashed',heatTriangles:String(heatTriangles),heatOpacity:String(state.opacity),nodeCount:String(state.nodes.length),labelCount:String(labels.length),routeCount:String(state.layers.routes?state.routeLines.length:0),zoneCount:String(state.layers.zones?SITE_AREAS.length+SITE_PATHS.length:0),contours:String(state.layers.contours),coordinates:String(state.layers.coordinates),nodePositions:JSON.stringify(state.nodes.map(n=>({id:n.id,x:n.x,y:n.y,agl:n.agl??KIND_META[n.kind].agl,world:world(n.x,n.y,n.agl??KIND_META[n.kind].agl).toArray()})))});
 }
 function fit(){const c=world(center.x,center.y),vertical=Math.max(bounds.maxY-bounds.minY,(bounds.maxX-bounds.minX)/Math.max(camera.aspect,.35)),d=Math.max(35,vertical*1.18);controls.target.copy(c);const v=state.view==='north'?[0,d*.78,-d]:state.view==='east'?[d,d*.78,0]:state.view==='west'?[-d,d*.78,0]:state.view==='top'?[0,d*1.4,.01]:[0,d*.78,d];camera.position.copy(c).add(new THREE.Vector3(...v as [number,number,number]));camera.lookAt(c);controls.update();}
 function update(s:SceneState){state=s;const layers=JSON.stringify(s.layers),target=JSON.stringify(s.params.targetPolygon??null);if(s.imagery!==imageKey){imageKey=s.imagery;const id=++loadId;new THREE.TextureLoader().load(s.imagery,t=>{if(!alive||id!==loadId){t.dispose();return;}t.colorSpace=THREE.SRGBColorSpace;material.map?.dispose();material.map=t;material.needsUpdate=true;renderer.domElement.dataset.imageryLoaded=s.imagery;const loaded=t.image as HTMLImageElement;renderer.domElement.dataset.imageryDimensions=`${loaded.naturalWidth||loaded.width}x${loaded.naturalHeight||loaded.height}`;requestRender();},undefined,()=>host.dispatchEvent(new CustomEvent('imagery-error')));}
  if(s.heat!==previousHeat||s.nodes!==previousNodes||s.overlay!==previousOverlay||layers!==previousLayerKey||s.routeLines!==previousRoutes||s.selectedId!==previousSelection||s.opacity!==previousOpacity||target!==previousTarget){rebuild();previousHeat=s.heat;previousNodes=s.nodes;previousOverlay=s.overlay;previousLayerKey=layers;previousRoutes=s.routeLines;previousSelection=s.selectedId;previousOpacity=s.opacity;previousTarget=target;}
  if(lastView!==s.view||lastFit!==s.fitKey){fit();lastView=s.view;lastFit=s.fitKey;}const focus=JSON.stringify(s.focus);if(focus!==lastFocus&&s.focus){const next=world(s.focus.x,s.focus.y),delta=next.clone().sub(controls.target);controls.target.copy(next);camera.position.add(delta);controls.update();}lastFocus=focus;requestRender();
 }
 let lastWidth=0,lastHeight=0;const resize=()=>{const r=host.getBoundingClientRect();const previousAspect=camera.aspect;renderer.setSize(Math.max(r.width,1),Math.max(r.height,1));camera.aspect=Math.max(r.width,1)/Math.max(r.height,1);camera.updateProjectionMatrix();if(lastWidth&&lastHeight&&r.width>0&&r.height>0&&previousAspect!==camera.aspect){const factor=Math.max(1,1/camera.aspect)/Math.max(1,1/previousAspect);camera.position.sub(controls.target).multiplyScalar(factor).clampLength(controls.minDistance,controls.maxDistance).add(controls.target);controls.update();}lastWidth=r.width;lastHeight=r.height;requestRender();};const observer=new ResizeObserver(resize);observer.observe(host);resize();update(initial);
 const raycaster=new THREE.Raycaster();let pointerStart:{x:number;y:number}|null=null;
 const hit=(e:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const intersection=raycaster.intersectObject(land)[0];return intersection?{x:intersection.point.x+(COLS-1)/2,y:intersection.point.z+(ROWS-1)/2}:null;};
 const down=(e:PointerEvent)=>{if(e.button===0)pointerStart={x:e.clientX,y:e.clientY};};
 const move=(e:PointerEvent)=>{if(pointerStart&&Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>4)pointerStart=null;const p=hit(e);state.onCursor?.(p);if(state.layers.coordinates){coordinate.textContent=p?`${gridToLl(p.x,p.y).map(v=>v.toFixed(5)).join(', ')} · ${elevBilinear(p.x,p.y).toFixed(0)} m elevation`:'Move over terrain for coordinates';}};
 const up=(e:PointerEvent)=>{if(pointerStart&&Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)<=4){const p=hit(e);if(p)state.onInspect(p);}pointerStart=null;};const leave=()=>{pointerStart=null;state.onCursor?.(null);};
 renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',leave);renderer.domElement.addEventListener('pointerleave',leave);
 const contextLost=(e:Event)=>{e.preventDefault();host.dispatchEvent(new CustomEvent('webgl-failed'));};renderer.domElement.addEventListener('webglcontextlost',contextLost);
 return {update,zoom(factor){camera.position.sub(controls.target).multiplyScalar(factor).clampLength(controls.minDistance,controls.maxDistance).add(controls.target);controls.update();requestRender();},destroy(){alive=false;++loadId;cancelAnimationFrame(raf);observer.disconnect();controls.removeEventListener('change',requestRender);controls.dispose();disposeObjects();geometry.dispose();material.map?.dispose();material.dispose();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointercancel',leave);renderer.domElement.removeEventListener('pointerleave',leave);renderer.domElement.removeEventListener('webglcontextlost',contextLost);renderer.dispose();renderer.domElement.remove();labelHost.remove();leaderHost.remove();coordinate.remove();}};
}
