import {createFileRoute} from '@tanstack/react-router';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {RadioTower,Settings2} from 'lucide-react';
import {ValleyMap} from '../components/valley-map';
import {PlanWorkbench} from '../components/plan-workbench';
import type {ScenarioChoice} from '../lib/scenario-view';
import {SidePanel} from '../components/side-panel';
import {EquipmentControls} from '../components/equipment-controls';
import {PathInspector} from '../components/path-inspector';
import {useSim,parseScenario,type Scenario} from '../lib/store';
import {MODEL_VERSION,type SimParams} from '../lib/radio';
import {SITE_VERSION} from '../lib/site-features';
import {TERRAIN_VERSION} from '../lib/terrain';
import {createStarterScenario,STARTER_PLAN,samePlan} from '../lib/starter-plan';
import {resolveStartup,SCENARIO_STORAGE,LEGACY_STORAGE,BACKUP_STORAGE,REJECTED_STORAGE} from '../lib/startup';
import {type InventorySettings} from '../lib/equipment';
import {inventoryLocks,withRoamingTests} from '../lib/planning-state';
import type {InfrastructurePlan} from '../lib/infrastructure-planner';
import type {Analysis,WorkerRequest} from '../lib/planner-worker';
export const Route=createFileRoute('/')({component:Home});
function Home(){
 const s=useSim(),paramKey=JSON.stringify(s.params()),params=useMemo<SimParams>(()=>JSON.parse(paramKey),[paramKey]);
 const worker=useRef<Worker|null>(null),request=useRef(0),scheduled=useRef<ReturnType<typeof setTimeout>|null>(null),activeKind=useRef<WorkerRequest['kind']|null>(null),importRef=useRef<HTMLInputElement>(null);
 const [customizing,setCustomizing]=useState(false),[pathOpen,setPathOpen]=useState(false),[backup,setBackup]=useState<string|null>(null),[preserved,setPreserved]=useState<string|null>(null);
 const [plan,setPlan]=useState<InfrastructurePlan|null>(STARTER_PLAN??null),[analysis,setAnalysis]=useState<Analysis|null>(null),[preview,setPreview]=useState<ScenarioChoice|null>(null),[previewAnalysis,setPreviewAnalysis]=useState<Analysis|null>(null);
 const previewNodes=preview?.nodes??null;
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('Preparing your computed plan…'),[error,setError]=useState(''),[storageError,setStorageError]=useState(''),[ready,setReady]=useState(false),[canPersist,setCanPersist]=useState(false);
 const snapshot=():Scenario=>({schema:3,siteVersion:SITE_VERSION,name:s.name,terrainVersion:TERRAIN_VERSION,modelVersion:MODEL_VERSION,nodes:s.nodes,params,inventory:s.inventory});
 const cancel=useCallback(()=>{if(scheduled.current)clearTimeout(scheduled.current);scheduled.current=null;worker.current?.terminate();worker.current=null;activeKind.current=null;request.current++;setBusy(false);setMessage('Calculation cancelled; your applied plan is unchanged.');},[]);
 const run=useCallback((kind:WorkerRequest['kind'],extra:Partial<WorkerRequest>={})=>{
  if(scheduled.current)clearTimeout(scheduled.current);scheduled.current=null;worker.current?.terminate();const id=++request.current;activeKind.current=kind;setBusy(true);setError('');setMessage(kind==='plan'?'Computing the best configuration for your available radios…':kind==='preview'?'Calculating this alternative…':'Updating roaming coverage…');
  const w=new Worker(new URL('../lib/planner-worker.ts',import.meta.url),{type:'module'});worker.current=w;
  w.onmessage=e=>{const d=e.data;if(d.id!==request.current)return;if(d.kind==='progress'){setMessage(d.message);return;}activeKind.current=null;setBusy(false);if(d.kind==='error'){setError(d.message);setMessage('Adjust the conflicting constraint, then compute again.');}else if(d.kind==='plan'){const result=d.result as InfrastructurePlan;try{const merged=withRoamingTests(result.nodes,useSim.getState().nodes);useSim.getState().applyPlan(merged,result.params,result.inventory);setPlan(result);setAnalysis(d.analysis);setPreview(null);setPreviewAnalysis(null);setMessage(`Best found across ${result.evaluations} evaluated layouts.`);}catch(e){setError(e instanceof Error?e.message:'Unable to preserve existing radios.');setMessage('Your applied plan is unchanged.');}}else if(d.kind==='preview'){setPreviewAnalysis(d.result);setMessage('Alternative ready for review.');}else{setAnalysis(d.result);useSim.getState().setHeat(d.result.heat);setMessage('Current configuration calculated.');}w.terminate();worker.current=null;};
  w.onerror=e=>{if(id!==request.current)return;activeKind.current=null;setBusy(false);setError(e.message||'Calculation worker failed.');w.terminate();worker.current=null;};
  w.postMessage({id,kind,nodes:s.nodes,params,...extra});
 },[s.nodes,params]);
 useEffect(()=>{try{const current=localStorage.getItem(SCENARIO_STORAGE),legacy=current===null?localStorage.getItem(LEGACY_STORAGE):null,result=resolveStartup(current??legacy);setBackup(localStorage.getItem(BACKUP_STORAGE));if(result.rejected!==undefined){setPreserved(result.rejected);localStorage.setItem(`${REJECTED_STORAGE}-${Date.now()}`,result.rejected);setStorageError('Earlier saved contents could not be restored. Original bytes are preserved; the computed starting plan is shown.');}if(result.backup!==undefined){localStorage.setItem(BACKUP_STORAGE,result.backup);setBackup(result.backup);}if('notice' in result&&result.notice)setStorageError(result.notice);useSim.getState().restore(result.scenario);setCanPersist(true);}catch{setCanPersist(false);setStorageError('Storage is unavailable; original saved contents will not be overwritten. Export this plan to keep changes.');}setReady(true);return()=>{worker.current?.terminate();if(scheduled.current)clearTimeout(scheduled.current);};},[]);
 useEffect(()=>{if(!ready)return;worker.current?.terminate();request.current++;setPreview(null);setPreviewAnalysis(null);setAnalysis(null);useSim.getState().setHeat(null);scheduled.current=setTimeout(()=>run('analyze'),180);return()=>{if(scheduled.current)clearTimeout(scheduled.current);scheduled.current=null;};},[ready,run]);
 useEffect(()=>{if(!ready||!canPersist)return;try{localStorage.setItem(SCENARIO_STORAGE,JSON.stringify({schema:3,siteVersion:SITE_VERSION,name:s.name,terrainVersion:TERRAIN_VERSION,modelVersion:MODEL_VERSION,nodes:s.nodes,params,inventory:s.inventory}));}catch{setStorageError('Storage is full. Export your plan to preserve changes.');}},[s.nodes,params,s.inventory,s.name,ready,canPersist]);
 const remember=()=>{const value=JSON.stringify(snapshot());setBackup(value);try{localStorage.setItem(BACKUP_STORAGE,value);}catch{setStorageError('Previous plan is available for this visit only; export it to preserve it.');}};
 const download=(content=JSON.stringify(snapshot(),null,2),name='ridgemesh-plan.json')=>{const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const compute=(inventory:InventorySettings=s.inventory)=>{setPreview(null);setPreviewAnalysis(null);try{run('plan',{inventory,lockedNodes:inventoryLocks(s.nodes,inventory)});}catch(e){setError(e instanceof Error?e.message:'Check locked equipment.');}};
 const toggleCustomize=()=>{if(customizing){if(activeKind.current==='preview')cancel();setPreview(null);setPreviewAnalysis(null);setPathOpen(false);}setCustomizing(!customizing);s.select(null);s.setFocusPoint(null);s.setTool('select');};
 const matches=plan&&JSON.stringify(plan.inventory)===JSON.stringify(s.inventory)&&samePlan({nodes:s.nodes,params},{nodes:plan.nodes,params:plan.params}),currentPlan=matches?plan:null;
 const shown=preview?previewAnalysis:analysis;
 const previewScenario=(choice:ScenarioChoice|null)=>{if(activeKind.current==='preview')cancel();setPreview(choice);setPreviewAnalysis(null);if(choice)run('preview',{nodes:choice.nodes,params:choice.params});};
 const applyPreview=()=>{if(!preview||!previewAnalysis)return;try{const next=withRoamingTests(preview.nodes,s.nodes);remember();cancel();s.applyPlan(next,preview.params,preview.inventory);setPreview(null);setPreviewAnalysis(null);}catch(e){setError(e instanceof Error?e.message:'Unable to preserve existing radios.');}};
 const editRadio=(id:string)=>{s.select(id);setCustomizing(true);};
 return <main className={`planner-shell progressive-planner inventory-planner terrain-planner ${customizing?'is-customizing':''}`}>
 <header className="app-header"><a className="brand" href="/" aria-label="RidgeMesh home"><span className="brand-mark"><RadioTower size={23}/></span><span>RidgeMesh<small>ASTRAL VALLEY</small></span></a><span className="model-badge">Planning estimate</span><div className="header-actions"><details className="plan-menu" onClick={e=>{if((e.target as HTMLElement).closest('button'))e.currentTarget.open=false;}}><summary>Plan</summary><div><button onClick={()=>download()}>Export plan</button><button onClick={()=>importRef.current?.click()}>Import plan</button><button onClick={()=>{remember();cancel();s.restore(createStarterScenario());setPlan(STARTER_PLAN);setCustomizing(false);}}>Load computed starting plan</button>{backup&&<button onClick={()=>{try{const old=parseScenario(backup,TERRAIN_VERSION,MODEL_VERSION);remember();cancel();s.restore(old);}catch(e){setError(e instanceof Error?e.message:'Previous plan unavailable');}}}>Restore previous plan</button>}{preserved!==null&&<button onClick={()=>download(preserved,'preserved-ridgemesh-plan.json')}>Download preserved file</button>}</div></details><input ref={importRef} aria-label="Import scenario file" type="file" accept=".json,application/json" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const raw=await f.text(),d=parseScenario(raw,TERRAIN_VERSION,MODEL_VERSION);if(JSON.parse(raw).schema===2||JSON.parse(raw).modelVersion!==MODEL_VERSION){setPreserved(raw);localStorage.setItem(`ridgemesh-import-original-${Date.now()}`,raw);setStorageError('Previous-format import migrated; its original file is preserved and available from Plan.');}remember();cancel();s.restore(d);setError('');}catch(x){setError(x instanceof Error?x.message:'Invalid plan');}e.target.value='';}}/></div></header>
 <section className="plan-overview" aria-label="Plan overview"><div><p className="eyebrow">ASTRAL VALLEY · FIXED RADIO PLANNING</p><h1>Find the best radio layout for this landscape.</h1><p className="planning-purpose">Start with the recommended network. Compare router locations, see how repeaters change coverage, then place your radios.</p></div><div className="planning-actions"><button onClick={()=>{const el=document.querySelector<HTMLDetailsElement>('.equipment-disclosure');if(el){el.open=true;el.scrollIntoView({behavior:'smooth',block:'start'});}}}>Equipment & constraints</button><button className="customize-button" aria-pressed={customizing} onClick={toggleCustomize}><Settings2 size={16}/>{customizing?'Done customizing':'Customize plan'}</button></div></section>
 <div className="workspace"><div className="map-column">{preview&&<div className="preview-summary"><div><strong>{preview.title} · not applied</strong><span>{previewAnalysis?`${Math.round(previewAnalysis.stats.meshLikelyFrac*100)}% strong roaming coverage`:'Calculating this scenario…'}</span></div><button disabled={!previewAnalysis} onClick={applyPreview}>Apply this scenario</button><button onClick={()=>previewScenario(null)}>Close preview</button></div>}
 <ValleyMap previewNodes={previewNodes} previewHeat={previewAnalysis?.heat??null} previewParams={preview?.params} editing={customizing} onEdit={()=>setCustomizing(true)}/>{customizing&&<details className="path-disclosure" onToggle={e=>setPathOpen(e.currentTarget.open)}><summary>Inspect a radio path and required mast height</summary>{pathOpen&&<PathInspector/>}</details>}<div className="compute-status" role="status"><span className={busy?'status-spinner':'status-dot'}/>{message}{busy&&<button onClick={cancel}>Cancel</button>}</div>{(error||storageError)&&<div className="error-banner" role="alert">{error||storageError}</div>}</div><div className="planning-sidebar">{customizing?<><div className="editor-heading"><strong>Edit the applied network</strong><button onClick={toggleCustomize}>Back to scenarios</button></div><SidePanel analysis={analysis} plan={currentPlan} busy={busy} onCompute={()=>compute()} onPreview={nodes=>previewScenario(nodes?{id:'advanced-alternative',title:'Alternate placement',detail:'Computed primary-site alternative',nodes,params,inventory:s.inventory}:null)}/></>:<PlanWorkbench nodes={s.nodes} params={params} inventory={s.inventory} plan={currentPlan} analysis={shown} appliedAnalysis={analysis} preview={preview} busy={busy} onPreview={previewScenario} onApply={applyPreview} onEdit={editRadio} onCompute={compute}/>}</div></div>
 <EquipmentControls inventory={s.inventory} busy={busy} onCompute={compute}/>
 <footer className="app-footer"><span>Best found within the current inventory and site constraints. Predicted RF coverage; field checks are still required.</span><a href="https://www.reddit.com/r/NocturnalValley/comments/1wdxd53/meshtastic_lora_will_be_onsite/" target="_blank" rel="noreferrer">Event equipment discussion ↗</a></footer>
 </main>;
}
