import { createFileRoute } from '@tanstack/react-router';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Download, Upload, Undo2, RadioTower, MousePointer2, Plus, Trash2, FileCheck2 } from 'lucide-react';
import { ValleyMap } from '../components/valley-map';
import { PathInspector } from '../components/path-inspector';
import { SidePanel } from '../components/side-panel';
import { useSim, parseScenario, type Scenario, type Preset } from '../lib/store';
import { MODEL_VERSION, type SimParams } from '../lib/radio';
import { TERRAIN_VERSION } from '../lib/terrain';
import { SITE_VERSION } from '../lib/site-features';
import type { Node } from '../lib/radio';
import type { Analysis, WorkerRequest } from '../lib/planner-worker';
import type { Candidate, OptimizeResult } from '../lib/optimizer';
export const Route=createFileRoute('/')({component:Home});
const STORAGE='ridgemesh-scenario-v2';
function Home(){
 const s=useSim();const key=JSON.stringify(s.params());const params=useMemo<SimParams>(()=>JSON.parse(key),[key]);const worker=useRef<Worker|null>(null);const request=useRef(0);const scheduled=useRef<ReturnType<typeof setTimeout>|null>(null);const importRef=useRef<HTMLInputElement>(null);
 const [previewNodes,setPreviewNodes]=useState<Node[]|null>(null);const [previewAnalysis,setPreviewAnalysis]=useState<Analysis|null>(null);const [bestPreview,setBestPreview]=useState<Analysis|null>(null);
 const [analysis,setAnalysis]=useState<Analysis|null>(null);const [comparisons,setComparisons]=useState<Array<{preset:Preset}&Analysis>>([]);const [optimization,setOptimization]=useState<OptimizeResult|null>(null);
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('Preparing terrain and radio model…');const [elapsed,setElapsed]=useState<number|null>(null);const [error,setError]=useState('');const [ready,setReady]=useState(false);
 const run=useCallback((kind:WorkerRequest['kind'],extra:Partial<WorkerRequest>={})=>{
  if(scheduled.current){clearTimeout(scheduled.current);scheduled.current=null;}worker.current?.terminate();const id=++request.current;setBusy(true);setError('');setMessage(kind==='preview'?'Calculating proposed layout…':kind==='analyze'?'Computing two-way coverage…':kind==='compare'?'Comparing four configurations…':'Searching feasible placement options…');
  const w=new Worker(new URL('../lib/planner-worker.ts',import.meta.url),{type:'module'});worker.current=w;
  w.onmessage=e=>{const d=e.data;if(d.id!==request.current)return;if(d.kind==='progress'){setMessage(d.message);return;}setBusy(false);setElapsed(d.elapsed??null);if(d.kind==='error'){setError(d.message);setMessage('Calculation needs attention');}else{setMessage(d.kind==='preview'?'Proposed layout calculated':'Current scenario calculated');if(d.kind==='analyze'){setAnalysis(d.result);useSim.getState().setHeat(d.result.heat);}if(d.kind==='compare')setComparisons(d.result);if(d.kind==='optimize'){setOptimization(d.result);setPreviewNodes(d.result.best.nodes);setBestPreview(d.preview);setPreviewAnalysis(d.preview);}if(d.kind==='preview')setPreviewAnalysis(d.result);;}w.terminate();worker.current=null;};
  w.onerror=e=>{if(id!==request.current)return;setBusy(false);setError(e.message||'Worker could not start.');setMessage('Calculation failed');w.terminate();worker.current=null;};
  w.postMessage({id,kind,nodes:s.nodes,params,...extra});
 },[s.nodes,params]);
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE);if(saved)useSim.getState().restore(parseScenario(saved,TERRAIN_VERSION,MODEL_VERSION));else if(localStorage.getItem('ridgemesh-scenario-v1'))setMessage('Event locations updated. Your earlier plan remains saved separately.');}catch(e){setError(e instanceof Error?e.message:'Saved scenario could not be restored.');}setReady(true);return()=>{if(scheduled.current)clearTimeout(scheduled.current);worker.current?.terminate();};},[]);
 useEffect(()=>{if(!ready)return;setAnalysis(null);setComparisons([]);setOptimization(null);setPreviewNodes(null);setPreviewAnalysis(null);setBestPreview(null);useSim.getState().setHeat(null);worker.current?.terminate();request.current++;setBusy(true);setMessage('Updating your plan…');scheduled.current=setTimeout(()=>run('analyze'),180);return()=>{if(scheduled.current)clearTimeout(scheduled.current);scheduled.current=null;};},[run,ready]);
 useEffect(()=>{if(!ready)return;const scenario:Scenario={schema:2,siteVersion:SITE_VERSION,name:s.name,terrainVersion:TERRAIN_VERSION,modelVersion:MODEL_VERSION,nodes:s.nodes,params};try{localStorage.setItem(STORAGE,JSON.stringify(scenario));}catch{setError('Browser storage is full. Export your scenario to preserve it.');}},[s.nodes,params,s.name,ready]);
 const download=()=>{const d:Scenario={schema:2,siteVersion:SITE_VERSION,name:s.name,terrainVersion:TERRAIN_VERSION,modelVersion:MODEL_VERSION,nodes:s.nodes,params};const url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ridgemesh-scenario.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const cancel=()=>{if(scheduled.current){clearTimeout(scheduled.current);scheduled.current=null;}worker.current?.terminate();worker.current=null;request.current++;setBusy(false);setMessage('Calculation cancelled');};
 const shown=previewNodes?previewAnalysis:analysis;
 const reached=shown?.pois.mesh.filter(p=>p.status==='likely'||p.status==='marginal').length;
 return <main className="planner-shell">
  <header className="app-header"><a className="brand" href="/" aria-label="RidgeMesh home"><span className="brand-mark"><RadioTower size={24}/></span><span>RidgeMesh<small>ASTRAL VALLEY · MISSOURI</small></span></a><div className="header-status"><span className="live-dot"/>Astral Valley · event planner <span className="model-badge">Planning estimate</span></div><div className="header-actions"><button onClick={download}><Download size={15}/>Export</button><button onClick={()=>importRef.current?.click()}><Upload size={15}/>Import</button><input ref={importRef} aria-label="Import scenario file" type="file" accept=".json,application/json" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=parseScenario(await f.text(),TERRAIN_VERSION,MODEL_VERSION);s.restore(d);setError('');}catch(x){setError(x instanceof Error?x.message:'Invalid scenario');}e.target.value='';}}/></div></header>
  <div className="workspace-heading"><div><p className="eyebrow">TERRAIN-AWARE NETWORK PLANNING</p><h1>Plan the network you will actually install.</h1><p className="subtitle">Place your radios. Check the gaps. Find the lowest useful mast at each relay site.</p></div><div className="source-stamp"><FileCheck2 size={18}/><span>2025 event locations<small>Checked against aerial imagery · source DEM terrain</small></span></div></div>
  <div className="workspace"><div className="map-column">
   <div className="placement-toolbar"><div className="tool-buttons"><button className={s.tool==='select'?'active':''} onClick={()=>s.setTool('select')}><MousePointer2 size={14}/>Select / move</button><button className={s.tool==='m1'?'active':''} onClick={()=>s.setTool('m1')}><Plus size={14}/>M1</button><button className={s.tool==='v4'?'active':''} onClick={()=>s.setTool('v4')}><Plus size={14}/>V4 relay</button><button className={s.tool==='totem'?'active':''} onClick={()=>s.setTool('totem')}><Plus size={14}/>Compass</button><button title="Erase a node" aria-label="Erase a node" className={s.tool==='erase'?'active':''} onClick={()=>s.setTool('erase')}><Trash2 size={14}/></button><button aria-label="Undo node change" disabled={!s.history.length} onClick={s.undo}><Undo2 size={14}/></button></div></div>
   <div className="planning-context"><strong>{params.mode==='crew'?'Connect every crew endpoint':`Reach base: ${s.nodes.find(n=>n.id===params.meshRootId)?.label??'place a base'}`}</strong><span>Two-way mesh · {params.receiverAgl??1.5} m handheld receiver · event-use areas</span></div>
   {previewNodes&&!previewAnalysis&&<div className="preview-summary" role="status">Calculating proposed coverage…<button onClick={()=>{cancel();setPreviewNodes(null);setPreviewAnalysis(null);}}>Close preview</button></div>}
   {previewNodes&&previewAnalysis&&<div className="preview-summary"><div><strong>Proposed layout · not applied</strong><span>Strong coverage {Math.round((analysis?.stats.meshLikelyFrac??0)*100)}% → {Math.round(previewAnalysis.stats.meshLikelyFrac*100)}% · weak {Math.round((analysis?.stats.meshMarginalFrac??0)*100)}% → {Math.round(previewAnalysis.stats.meshMarginalFrac*100)}%</span></div><button onClick={()=>s.replaceNodes(previewNodes)}>Apply preview</button><button onClick={()=>{setPreviewNodes(null);setPreviewAnalysis(null);}}>Close preview</button></div>}
   <ValleyMap previewNodes={previewNodes} previewHeat={previewAnalysis?.heat??null}/>
   <div className="map-legend"><span><i className="legend-blue"/>Strong</span><span><i className="legend-amber"/>Weak</span><span><i className="legend-red"/>No route</span><span><i className="legend-hatch"/>Unknown</span><span>Coverage samples are opt-in · select a device or site to see its route</span></div>
   <div className="summary-strip"><div><small>STRONG MESH COVERAGE</small><strong>{shown?`${Math.round(shown.stats.meshLikelyFrac*100)}%`:'—'}</strong><span>at {params.receiverAgl??1.5} m receiver height</span></div><div><small>WEAK COVERAGE</small><strong>{shown?`${Math.round(shown.stats.meshMarginalFrac*100)}%`:'—'}</strong><span>less than 6 dB reserve</span></div><div><small>EVENT SITES REACHED</small><strong>{shown?`${reached} / ${shown.pois.mesh.length}`:'—'}</strong><span>both directions required</span></div><div><small>RELAYS IN YOUR PLAN</small><strong>{s.nodes.filter(n=>n.kind==='v4').length}</strong><span>{s.nodes.filter(n=>n.kind!=='v4').length} handheld endpoints</span></div></div>
   <PathInspector/>
   <div className="compute-status" role="status"><span className={busy?'status-spinner':'status-dot'}/>{message}{elapsed!==null&&!busy&&<span className="elapsed">{(elapsed/1000).toFixed(2)} s</span>}{busy&&<button onClick={cancel}>Cancel</button>}{!busy&&!analysis&&<button onClick={()=>run('analyze')}>Recalculate</button>}</div>
   {error&&<div className="error-banner" role="alert">{error}</div>}
  </div><SidePanel analysis={analysis} comparisons={comparisons} optimization={optimization} busy={busy} message={message} onCompare={()=>run('compare',{nodes:previewNodes??s.nodes})} onOptimize={(budget:number,candidates:Candidate[])=>run('optimize',{budget,candidates})} onCancel={cancel} onPreviewLayout={nodes=>{setPreviewNodes(nodes);if(!nodes)setPreviewAnalysis(null);else if(nodes===optimization?.best.nodes&&bestPreview)setPreviewAnalysis(bestPreview);else{setPreviewAnalysis(null);run('preview',{nodes});}}}/></div>
  <footer className="app-footer"><span>Event-map locations are reconciled with aerial imagery; camp boundaries and radio predictions remain planning estimates.</span><a href="/data/terrain-manifest.json" target="_blank" rel="noreferrer">View source manifest ↗</a></footer>
 </main>;
}
