import {test} from 'node:test';
import assert from 'node:assert/strict';
import {computeHeat,planningTargets,coverageStats,suggestClients} from '../src/lib/radio';
import {SITE_POINTS} from '../src/lib/site-features';
import type {Environment} from '../src/lib/model';
const p:Environment={crowd:0,bagLoss:false,includeRoamingRelays:false,meshHops:3};
test('optimizer targets and heat share the polygon denominator including unknown cells',()=>{for(const params of [p,{...p,targetPolygon:[[10,10],[26,10],[26,26],[10,26]] as [number,number][]}]){const heat=computeHeat([],params,8),targets=planningTargets(params,8);assert.ok(targets.length>0);assert.ok(Math.abs(targets.reduce((sum,t)=>sum+t.weight!*10000,0)-heat.targetAreaSqM)<1e-6);const stats=coverageStats(heat,[]);assert.equal(stats.meshLikelyFrac,0);assert.equal(stats.meshMarginalFrac,0);assert.equal(stats.meshUnknownFrac,1);assert.equal(stats.meshUnavailableFrac,0);}});
test('starting handheld crew begins at source main stage and has unique source sites',()=>{const nodes=suggestClients(),stage=SITE_POINTS.find(p=>p.id==='stage')!;assert.equal(nodes[0].id,'m1-0');assert.equal(nodes[0].x,stage.x);assert.equal(nodes[0].y,stage.y);assert.equal(new Set(nodes.map(n=>`${n.x}:${n.y}`)).size,nodes.length);assert.ok(nodes.every(n=>n.kind==='m1'&&n.agl===1.5&&n.role==='client'));});
test('40 m target cells are populated; cells outside event areas remain unevaluated',()=>{const nodes=suggestClients(),heat=computeHeat(nodes,{...p,rootId:nodes[0].id},4),targets=planningTargets(p,4);assert.ok(targets.length>planningTargets(p,8).length);assert.equal(heat.targetWeights.filter(w=>w>0).length,targets.length);assert.ok(heat.targetWeights.some(w=>w===0));for(let i=0;i<heat.mesh.length;i++){if(heat.targetWeights[i]===0){assert.equal(heat.mesh[i],-1);assert.ok(Number.isNaN(heat.meshMargin[i]));}else assert.notEqual(heat.mesh[i],-1);}assert.ok(Math.abs(targets.reduce((sum,t)=>sum+t.weight!*10000,0)-heat.targetAreaSqM)<1e-6);});
