import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fsplDb,knifeEdgeDb,pathProfile,directedLink,routeBetween,evaluateTarget,type Surface,type RadioNode,type Environment} from '../src/lib/model';
const surface:Surface={version:'fixture',cellM:10,cols:1000,rows:1000,elevation:()=>0,cover:()=> 'forest'};
const p:Environment={crowd:0,bagLoss:false,includeRoamingRelays:true,meshHops:2,fadeDb:0,foliageDbPerM:0};
const a:RadioNode={id:'a',kind:'m1',x:0,y:0,label:'a',agl:2},b:RadioNode={...a,id:'b',x:100,txDbm:28};
test('independent FSPL and knife edge oracles',()=>{assert.ok(Math.abs(fsplDb(1000,915)-91.67)<.02);assert.ok(Math.abs(knifeEdgeDb(0)-6.03)<.02);assert.equal(knifeEdgeDb(-1),0);});
test('foliage is physical length independent of sample density',()=>{const x=pathProfile({...a,agl:2},{...b,agl:2},surface,3);const y=pathProfile({...a,agl:2},{...b,agl:2},surface,27);assert.ok(Math.abs(x.forestM-1000)<1e-8);assert.ok(Math.abs(x.forestM-y.forestM)<1e-8);assert.equal(x.blocked,false);});
test('directional transmitter power and unknown configuration',()=>{assert.ok(Math.abs(directedLink(b,a,p,surface).marginDb-directedLink(a,b,p,surface).marginDb-6)<1e-8);assert.equal(directedLink({...a,configurationKnown:false},b,p,surface).status,'unknown');assert.equal(directedLink(a,b,p,{...surface,elevation:()=>NaN}).status,'unknown');});
test('graph origin, mute, hop boundary, isolated island and separate reverse route',()=>{const c={...a,id:'c',x:200},island={...a,id:'island',x:500};const edge=(x:RadioNode,y:RadioNode)=>({...directedLink(x,y,p,surface),ok:Math.abs(x.x-y.x)<=100,status:Math.abs(x.x-y.x)<=100?'likely' as const:'unavailable' as const,marginDb:10});assert.deepEqual(routeBetween([a,b,c,island],'a','c',p,surface,edge).route,['a','b','c']);assert.equal(routeBetween([a,{...b,role:'mute'},c],'a','c',p,surface,edge).status,'unavailable');assert.equal(routeBetween([a,b,c],'a','c',{...p,meshHops:1},surface,edge).status,'unavailable');assert.equal(routeBetween([a,b,c,island],'a','island',p,surface,edge).status,'unavailable');assert.equal(evaluateTarget({id:'t',label:'t',x:500,y:0},[a,b,c,island],{...p,rootId:'a'},surface,'mesh',edge).status,'unavailable');});
test('ridge position changes diffraction by Fresnel geometry',()=>{const left={...surface,cover:()=> 'field',elevation:(x:number)=>Math.abs(x-20)<.1?8:0};const mid={...left,elevation:(x:number)=>Math.abs(x-50)<.1?8:0};assert.notEqual(directedLink(a,b,p,left).diffractionDb,directedLink(a,b,p,mid).diffractionDb);});
test('one-way RF never becomes bidirectional coverage; incompatible modem stays unavailable',()=>{const edge=(x:RadioNode,y:RadioNode)=>({...directedLink(x,y,p,surface),ok:x.id.startsWith('target:'),status:x.id.startsWith('target:')?'likely' as const:'unavailable' as const,marginDb:10});assert.equal(evaluateTarget({id:'point',label:'point',x:1,y:0},[a],{...p,rootId:'a'},surface,'mesh',edge).status,'unavailable');assert.equal(directedLink(a,{...b,modem:'different'},p,surface).status,'unavailable');assert.equal(directedLink({...a,gainDbi:NaN},b,p,surface).status,'unknown');});
test('deployment and real roles stay independent: fixed clients forward; roaming clients are optional; mute never forwards',()=>{
 const c={...a,id:'c',x:200},edge=(x:RadioNode,y:RadioNode)=>({...directedLink(x,y,p,surface),ok:Math.abs(x.x-y.x)<=100,status:Math.abs(x.x-y.x)<=100?'likely' as const:'unavailable' as const,marginDb:10});
 for(const role of ['client','client_base','router_late','router'] as const){const middle={...b,role,deployment:'fixed' as const};assert.equal(routeBetween([a,middle,c],'a','c',{...p,includeRoamingRelays:false},surface,edge).status,'likely',role);}
 assert.equal(routeBetween([a,{...b,role:'client',deployment:'roaming'},c],'a','c',{...p,includeRoamingRelays:false},surface,edge).status,'unavailable');
 assert.equal(routeBetween([a,{...b,role:'client',deployment:'roaming'},c],'a','c',{...p,includeRoamingRelays:true},surface,edge).status,'likely');
 assert.equal(routeBetween([a,{...b,role:'mute',deployment:'fixed'},c],'a','c',p,surface,edge).status,'unavailable');
});
