import {test} from 'node:test';import assert from 'node:assert/strict';
import {computeHeat,coverageStats,evaluateTarget,planningTargets,analysisSurface,directedLink} from '../src/lib/radio';
import {createStarterScenario} from '../src/lib/starter-plan';
import {useSim} from '../src/lib/store';
test('filled heat retains the exact two-way route margin and relay provenance at evaluated receiver cells',()=>{const s=createStarterScenario(),heat=computeHeat(s.nodes,s.params),targets=planningTargets(s.params);let relayArea=0;for(const target of targets){const [gx,gy]=target.id.split(':').map(Number),k=gy*heat.w+gx,r=evaluateTarget(target,s.nodes,s.params,analysisSurface,'mesh');assert.ok(Math.abs(heat.meshMargin[k]-r.marginDb)<1e-4);const usesRelay=Number(r.forward.route.length>2||r.reverse.route.length>2);assert.equal(heat.meshViaRelay[k],usesRelay);relayArea+=usesRelay*heat.targetWeights[k];}assert.equal(coverageStats(heat,s.nodes).meshRelayFrac,relayArea/heat.targetAreaSqM);});
test('router-only and relocated-radio scenarios recompute the field; absent primary cannot be replaced by a disconnected support island',()=>{const s=createStarterScenario(),root=s.nodes.find(n=>n.id==='primary-p1')!,alone=computeHeat([root],s.params),moved=computeHeat([{...root,x:85,y:112,agl:9}],s.params);assert.equal(coverageStats(alone,[root]).meshRelayFrac,0);assert.ok(Array.from(alone.meshMargin).some((m,i)=>Number.isFinite(m)&&Number.isFinite(moved.meshMargin[i])&&Math.abs(m-moved.meshMargin[i])>1));const island=computeHeat(s.nodes.filter(n=>n.id!==root.id),s.params);assert.equal(coverageStats(island,s.nodes).meshFrac,0);assert.equal(coverageStats(island,s.nodes).meshRelayFrac,0);});
test('restore and explicit starter reset enable the requested heatmap instead of hiding coverage',()=>{const s=createStarterScenario();useSim.getState().setOverlay('none');useSim.getState().restore(s);assert.equal(useSim.getState().overlay,'mesh');useSim.getState().setOverlay('none');useSim.getState().loadPreset('backbone');assert.equal(useSim.getState().overlay,'mesh');});
test('MediumFast derived threshold reduces legacy link margin by exactly six dB and keeps individual overrides authoritative',()=>{const s=createStarterScenario(),[a,b]=s.nodes,old=directedLink(a,b,{...s.params,defaultRxDbm:-132},analysisSurface),event=directedLink(a,b,{...s.params,defaultRxDbm:-126},analysisSurface),overridden=directedLink(a,{...b,rxDbm:-132},{...s.params,defaultRxDbm:-126},analysisSurface);assert.equal(event.budgetDb,148+(a.gainDbi??2)+(b.gainDbi??0)-(s.params.fadeDb??8));assert.ok(Math.abs(old.marginDb-event.marginDb-6)<1e-9);assert.equal(overridden.marginDb,old.marginDb);});
test('landscape coverage evaluates approaches beyond camps without changing the event-area denominator or RF values',()=>{const s=createStarterScenario(),event=computeHeat(s.nodes,s.params,4),landscape=computeHeat(s.nodes,s.params,4,'landscape');assert.equal(landscape.targetAreaSqM,event.targetAreaSqM);assert.deepEqual(coverageStats(landscape,s.nodes),coverageStats(event,s.nodes));assert.ok(Array.from(landscape.meshMargin).some((m,i)=>!landscape.targetWeights[i]&&Number.isFinite(m)));for(let i=0;i<event.mesh.length;i++)if(event.targetWeights[i]){assert.equal(landscape.meshMargin[i],event.meshMargin[i]);assert.equal(landscape.mesh[i],event.mesh[i]);}});
