import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createStarterScenario,isStarterPlan,STARTER_EVIDENCE} from '../src/lib/starter-plan';
import {resolveStartup} from '../src/lib/startup';
import {parseScenario,type Scenario} from '../src/lib/store';
import {STARTER_PARAMS,STARTER_BUDGET,placementCandidates} from '../src/lib/placement-policy';
import {MODEL_VERSION,suggestClients,analyzeScenario,analysisSurface,planningTargets,routeBetween} from '../src/lib/radio';
import {TERRAIN_VERSION} from '../src/lib/terrain';
import {optimizePlacement} from '../src/lib/optimizer';

test('committed starter matches current bounded search, forwards both ways and preserves the crew base',()=>{
 const plan=createStarterScenario();assert.deepEqual(parseScenario(JSON.stringify(plan),TERRAIN_VERSION,MODEL_VERSION),plan);
 const clients=suggestClients();assert.deepEqual(plan.nodes.filter(n=>n.kind!=='v4'),clients);assert.equal(plan.params.meshRootId,clients[0].id);
 const result=optimizePlacement({nodes:clients,params:STARTER_PARAMS,candidates:placementCandidates(),targets:planningTargets(STARTER_PARAMS,4),budget:STARTER_BUDGET,surface:analysisSurface});
 assert.deepEqual(plan.nodes,result.best.nodes);assert.equal(result.best.score,STARTER_EVIDENCE.proposedScore);assert.ok(result.best.score>result.baseline.score);
 const routers=plan.nodes.filter(n=>n.role==='router');assert.equal(routers.length,1);
 for(const router of routers)for(const [from,to] of [[router.id,plan.params.meshRootId!],[plan.params.meshRootId!,router.id]])assert.ok(['likely','marginal'].includes(routeBetween(plan.nodes,from,to,plan.params,analysisSurface).status));
 const analysis=analyzeScenario(plan.nodes,plan.params,{step:4});assert.equal(analysis.stats.meshLikelyFrac,STARTER_EVIDENCE.likelyFraction);assert.equal(analysis.stats.targetAreaSqM,STARTER_EVIDENCE.targetAreaSqM);
});
test('fresh startup applies independent optimized snapshots; custom and empty saved plans win',()=>{
 const initial=resolveStartup(null);assert.equal(initial.source,'recommended');assert.ok(isStarterPlan(initial.scenario.nodes,initial.scenario.params));
 initial.scenario.nodes[0].agl=12;assert.equal(createStarterScenario().nodes[0].agl,1.5);
 for(const nodes of [initial.scenario.nodes,[]]){const custom:Scenario={...initial.scenario,name:'My saved decision',nodes};const result=resolveStartup(JSON.stringify(custom));assert.equal(result.source,'saved');assert.deepEqual(result.scenario,custom);}
});
test('only the exact legacy autogenerated starter upgrades, retaining original bytes',()=>{
 const old={...createStarterScenario(),name:'My event plan',nodes:suggestClients(),params:STARTER_PARAMS},raw=JSON.stringify(old);
 const upgraded=resolveStartup(raw);assert.equal(upgraded.source,'upgraded');assert.equal(upgraded.backup,raw);assert.ok(upgraded.scenario.nodes.some(n=>n.role==='router'));
 for(const changed of [{...old,name:'Intentional handheld crew'},{...old,params:{...old.params,receiverAgl:1.6}},{...old,nodes:old.nodes.map((n,i)=>i? n:{...n,x:n.x+.1})}])assert.equal(resolveStartup(JSON.stringify(changed)).source,'saved');
});
test('unreadable or incompatible saved content is returned intact for preservation, never discarded',()=>{
 for(const raw of ['', '{broken',JSON.stringify({...createStarterScenario(),siteVersion:'old-site'})]){const result=resolveStartup(raw);assert.equal(result.source,'recovered');assert.equal(result.rejected,raw);assert.ok(result.error);}
});
