import {useState} from 'react';
import {HARDWARE,isFixed,ROLE_LABELS,type Node,type SimParams} from '../lib/radio';
import {availableRadios,type InventorySettings} from '../lib/equipment';
import type {InfrastructurePlan} from '../lib/infrastructure-planner';
import type {Analysis} from '../lib/planner-worker';
import {placementChanges,radioCode,scenarioChoices,siteName,type ScenarioChoice} from '../lib/scenario-view';
const pct=(n:number|undefined)=>n===undefined?'—':`${Math.round(n*100)}%`;
export function PlanWorkbench({nodes,params,inventory,plan,analysis,appliedAnalysis,preview,busy,onPreview,onApply,onEdit,onCompute}:{nodes:Node[];params:SimParams;inventory:InventorySettings;plan:InfrastructurePlan|null;analysis:Analysis|null;appliedAnalysis:Analysis|null;preview:ScenarioChoice|null;busy:boolean;onPreview:(v:ScenarioChoice|null)=>void;onApply:()=>void;onEdit:(id:string)=>void;onCompute:(inventory:InventorySettings)=>void}){
 const [more,setMore]=useState(false),choices=scenarioChoices(nodes,params,inventory,plan),shownNodes=preview?.nodes??nodes,stats=analysis?.stats,changes=preview?placementChanges(nodes,preview.nodes):[];
 const fixed=shownNodes.filter(isFixed),primary=fixed.find(n=>n.id==='primary-p1');
 return <aside className="plan-workbench" aria-label="Plan recommendation and scenarios">
 <section className="recommendation-card"><p className="eyebrow">{preview?'SCENARIO PREVIEW':plan?'RECOMMENDED NETWORK':'APPLIED NETWORK'}</p><h2>{preview?.title??(primary?`${radioCode(primary,shownNodes)} at ${siteName(primary).replace(/ camp$/i,'')}`:'Place the main P1')}</h2><p>{preview?preview.detail:plan?`Best found across ${plan.evaluations} tested layouts for your equipment and allowed sites.`:'Your saved placements are applied. Recompute to compare the best network for the current constraints.'}</p>
 <div className="scenario-metrics"><div><strong>{pct(stats?.meshLikelyFrac??(!preview?plan?.likelyFraction:undefined))}</strong><span>strong event area</span></div><div><strong>{Number.isFinite(stats?.meshMinMarginDb)?`${stats!.meshMinMarginDb.toFixed(1)} dB`:'—'}</strong><span>weakest served margin</span></div><div><strong>{pct(stats?.meshRelayFrac)}</strong><span>area using a relay</span></div></div>
 {preview&&appliedAnalysis&&stats&&<p className="scenario-delta">{((stats.meshLikelyFrac-appliedAnalysis.stats.meshLikelyFrac)*100).toFixed(0)} percentage-point change in strong area; {Number.isFinite(stats.meshMinMarginDb)&&Number.isFinite(appliedAnalysis.stats.meshMinMarginDb)?`${(stats.meshMinMarginDb-appliedAnalysis.stats.meshMinMarginDb).toFixed(1)} dB change in weakest served margin.`:'some routes are unavailable or unknown.'}</p>}
 {!preview&&plan&&<p className="recommendation-reason">{pct(plan.redundantFraction)} with 2+ access nodes · {plan.reserve} radio{plan.reserve===1?'':'s'} in reserve.</p>}
 <details className="metric-explanation"><summary>How to read these results</summary><p className="metric-note">{(preview?.params??params).defaultRxDbm===-126?'AstralMesh MediumFast baseline · −126 dBm. ':'Custom receiver assumptions. '}Strong: ≥6 dB two-way margin. Relay use describes the selected route, not extra coverage. Both access options still depend on the primary P1. Coverage percentages describe event-use areas; the map also evaluates the surrounding landscape. Unused stock stays in reserve when it does not improve the search objective.</p></details>
 {preview&&<><ul className="placement-changes">{changes.map((change,i)=><li key={i}>{change}</li>)}</ul><div className="scenario-apply"><button className="primary-button" disabled={busy||!analysis} onClick={onApply}>Apply this scenario</button><button onClick={()=>onPreview(null)}>Return to applied plan</button></div></>}
 </section>
 <section className="deployment-card"><h3>{preview?'Proposed deployment':'Fixed deployment'} <span>{fixed.length} radios</span></h3><ol>{fixed.map(n=><li key={n.id}><button disabled={Boolean(preview)} onClick={()=>onEdit(n.id)}><b className="deployment-code">{radioCode(n,shownNodes)}</b><span><strong>{HARDWARE[n.kind].title}</strong><small>{siteName(n)} · {n.agl??HARDWARE[n.kind].agl} m AGL</small><small>{ROLE_LABELS[n.role??'client']}{n.locked?' · locked':''}</small></span><span aria-hidden="true">↗</span></button></li>)}</ol><p className="metric-note">Select a radio to change its placement or height. Mounts and sunlight need field confirmation.</p></section>
 <section className="scenario-picker"><div className="section-heading"><h3>Compare scenarios</h3><span>Preview → inspect → apply</span></div><button className={`scenario-option ${!preview?'selected':''}`} aria-pressed={!preview} onClick={()=>onPreview(null)}><strong>{plan?'Recommended network':'Applied network'}</strong><small>{nodes.filter(isFixed).length} fixed radios · your saved configuration</small></button>{(more?choices:choices.slice(0,3)).map(choice=><button key={choice.id} className={`scenario-option ${preview?.id===choice.id?'selected':''}`} disabled={busy} aria-pressed={preview?.id===choice.id} onClick={()=>onPreview(choice)}><strong>{choice.title}</strong><small>{choice.detail}</small>{choice.strong!==undefined&&<small>{pct(choice.strong)} strong · {pct(choice.access)} with 2+ access nodes</small>}</button>)}{choices.length>3&&<button className="text-action" onClick={()=>setMore(!more)}>{more?'Show fewer scenarios':`Show all ${choices.length} alternatives`}</button>}{!plan&&<p className="metric-note">Recompute to get alternate primary sites for your latest placements and locks.</p>}</section>
 <section className="scale-card" aria-label="Scale the network"><h3>Scale the fixed network</h3><div className="budget-stepper"><button aria-label="Use fewer fixed radios" disabled={busy||inventory.budget<=1} onClick={()=>onCompute({...inventory,budget:inventory.budget-1})}>−</button><output aria-label="Fixed-radio budget">{inventory.budget}</output><button aria-label="Use more fixed radios" disabled={busy||inventory.budget>=availableRadios(inventory)} onClick={()=>onCompute({...inventory,budget:inventory.budget+1})}>+</button><span>radio budget · P1 included</span></div><button className="recompute-plan" disabled={busy} onClick={()=>onCompute(inventory)}>Recompute best plan</button><p className="metric-note">{availableRadios(inventory)} available fixed radios · {inventory.roamingCount} roaming participants. Roaming people are not fixed repeaters.</p></section>
 <details className="relief-explanation"><summary>Actual relief · why 1×?</summary><p>One horizontal metre equals one vertical metre. Exaggeration can make shallow slopes easier to see, but distorts the landscape and adds no RF evidence. This planner now uses actual relief for both terrain and antenna heights.</p><p>The terrain is a 10 m analysis grid. The heatmap shows 40 m RF cells, not measured live signal strength.</p></details>
 </aside>;
}
