import { useMemo, useState, type ReactNode } from 'react';
import { POIS, COLS, ROWS } from '@/lib/terrain';
import { HARDWARE, MODEL_ASSUMPTIONS, MODEL_VERSION, type analyzeScenario, type Node, type Status } from '@/lib/radio';
import { useSim, type Preset, type Tool } from '@/lib/store';
import { type Candidate, type OptimizeResult } from '@/lib/optimizer';
import { FieldNotebook } from './field-notebook';

type Analysis=ReturnType<typeof analyzeScenario>;
export type SidePanelProps={analysis:Analysis|null;comparisons:Array<{preset:Preset}&Analysis>;optimization:OptimizeResult|null;busy:boolean;message:string;onCompare:()=>void;onOptimize:(budget:number,candidates:Candidate[])=>void;onCancel:()=>void};
const presetLabels:Record<Preset,string>={empty:'Empty canvas','totem-crew':'Totem crew','m1-only':'M1 crew',backbone:'V4-assisted M1',hybrid:'Hybrid · independent systems'};
const percent=(v:number)=>`${Math.round(v*100)}%`;
const margin=(v:number)=>Number.isFinite(v)?`${v.toFixed(1)} dB`:'—';
function Section({title,children}:{title:string;children:ReactNode}){return <section className="panel-section"><h3>{title}</h3>{children}</section>;}
function NumberField({label,value,onChange,min,max,step=1}:{label:string;value:number;onChange:(v:number)=>void;min:number;max:number;step?:number}){return <label className="field"><span>{label}</span><input type="number" min={min} max={max} step={step} value={value} onChange={e=>{if(e.target.value==='')return;const v=Number(e.target.value);if(Number.isFinite(v)&&v>=min&&v<=max)onChange(v);}}/></label>;}
function Badge({status}:{status:Status}){return <span className={`status status-${status}`}>{status}</span>;}
export function SidePanel({analysis,comparisons,optimization,busy,message,onCompare,onOptimize,onCancel}:SidePanelProps){
 const s=useSim();const p=s.params();const [tab,setTab]=useState<'network'|'placement'|'evidence'>('network');const [budget,setBudget]=useState(2);const [allowed,setAllowed]=useState<Record<string,boolean>>({});const [height,setHeight]=useState(6);
 const selected=s.nodes.find(n=>n.id===s.selected);const mesh=s.nodes.filter(n=>n.kind!=='totem');
 const candidates=useMemo<Candidate[]>(()=>POIS.filter(v=>v.kind==='camp'||v.kind==='stage'||v.kind==='gate'||v.kind==='amenity').map(v=>({id:`site-${v.id}-${height}`,siteId:v.id,node:{id:`recommended-${v.id}-${height}`,kind:'v4',x:v.x,y:v.y,agl:height,role:'router',label:`${v.label} relay`},allowed:allowed[v.id]??true,feasibility:'unknown',reason:'Inferred point; permission, access, power and mounting unverified.'})),[allowed,height]);
 const polygon=p.targetPolygon;const xs=polygon?.map(v=>v[0]),ys=polygon?.map(v=>v[1]);const bounds={west:xs?Math.min(...xs):0,east:xs?Math.max(...xs):COLS-1,north:ys?Math.min(...ys):0,south:ys?Math.max(...ys):ROWS-1};
 const setBounds=(key:keyof typeof bounds,value:number)=>{const b={...bounds,[key]:value};if(b.west<b.east&&b.north<b.south)s.setParams({targetPolygon:[[b.west,b.north],[b.east,b.north],[b.east,b.south],[b.west,b.south]]});};
 const update=(patch:Partial<Node>)=>selected&&s.updateNode(selected.id,patch);
 return <aside className="side-panel" aria-label="Coverage planner"><div className="panel-tabs" role="tablist" aria-label="Planner sections">{(['network','placement','evidence'] as const).map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>
 <div className="panel-status" aria-live="polite">{message}{busy&&<button onClick={onCancel}>Cancel calculation</button>}</div>
 {tab==='network'&&<>
 <Section title="Scenario"><label className="field"><span>Starting layout</span><select value="" onChange={e=>s.loadPreset(e.target.value as Preset)}><option value="" disabled>Load a complete preset…</option>{Object.entries(presetLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><div className="tool-grid">{(['select','m1','v4','totem','erase'] as Tool[]).map(t=><button aria-pressed={s.tool===t} onClick={()=>s.setTool(t)} key={t}>{t==='select'?'Select':t==='erase'?'Remove':`+ ${t.toUpperCase()}`}</button>)}<button onClick={s.undo} disabled={!s.history.length}>Undo placement</button></div><p className="muted">Choose a device, then tap the property map to place it. Select a node to inspect and edit it.</p></Section>
 <Section title="Communication target"><label className="field"><span>Required communication</span><select value={p.mode??'base'} onChange={e=>s.setParams({mode:e.target.value as 'base'|'crew'})}><option value="base">Reach the selected base · both directions</option><option value="crew">Reach every crew device · both directions</option></select></label><label className="field"><span>Mesh base</span><select value={p.meshRootId??mesh[0]?.id??''} onChange={e=>s.setParams({meshRootId:e.target.value})}><option value="" disabled>Select a base</option>{mesh.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label className="field"><span>Totem base</span><select value={p.totemRootId??s.nodes.find(n=>n.kind==='totem')?.id??''} onChange={e=>s.setParams({totemRootId:e.target.value})}><option value="" disabled>Select a Totem base</option>{s.nodes.filter(n=>n.kind==='totem').map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><p className="muted">Crew excludes fixed V4 relays. Hybrid networks remain independent; devices from different systems never relay for one another.</p></Section>
 <Section title={`Devices · ${s.nodes.length}`}><label className="field"><span>Edit device</span><select value={selected?.id??''} onChange={e=>s.select(e.target.value||null)}><option value="">Select a device…</option>{s.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label>{selected&&<><label className="field"><span>Label</span><input maxLength={100} value={selected.label} onChange={e=>update({label:e.target.value})}/></label><div className="field-grid"><NumberField label="Antenna AGL · m" value={selected.agl??HARDWARE[selected.kind].agl} min={.5} max={30} step={.5} onChange={agl=>update({agl})}/><NumberField label="TX power · dBm" value={selected.txDbm??HARDWARE[selected.kind].txDbm} min={-20} max={30} onChange={txDbm=>update({txDbm})}/><NumberField label="RX sensitivity · dBm" value={selected.rxDbm??HARDWARE[selected.kind].rxDbm} min={-150} max={-60} onChange={rxDbm=>update({rxDbm})}/><NumberField label="Antenna gain · dBi" value={selected.gainDbi??0} min={-10} max={20} step={.5} onChange={gainDbi=>update({gainDbi})}/><NumberField label="Cable loss · dB" value={selected.cableDb??0} min={0} max={20} step={.5} onChange={cableDb=>update({cableDb})}/><NumberField label="Frequency · MHz" value={selected.frequencyMhz??HARDWARE[selected.kind].mhz} min={100} max={6000} step={.1} onChange={frequencyMhz=>update({frequencyMhz})}/></div><label className="field"><span>Forwarding role</span><select value={selected.role??(selected.kind==='v4'?'router':'client')} onChange={e=>update({role:e.target.value as Node['role']})}><option value="client">Client · use forwarding switch</option><option value="router">Router · forwarding enabled</option><option value="mute">Mute · endpoint only</option></select></label><div className="field-grid"><label className="field"><span>Channel / group</span><input value={selected.channel??'default'} onChange={e=>update({channel:e.target.value})}/></label><label className="field"><span>Modem profile</span><input value={selected.modem??'default'} onChange={e=>update({modem:e.target.value})}/></label></div><div className="button-row"><button onClick={()=>s.toggleProbe(selected.id)}>Select for link probe</button><button onClick={()=>s.removeNode(selected.id)}>Remove device</button></div><p className="muted">Physical values are engineering assumptions until confirmed against your exact device, antenna and modem configuration.</p></>}</Section>
 <Section title="Environment & routing"><div className="field-grid"><NumberField label="Crowd · 0–1" value={p.crowd} min={0} max={1} step={.05} onChange={crowd=>s.setParams({crowd})}/><NumberField label="Fade allowance · dB" value={p.fadeDb??8} min={0} max={40} onChange={fadeDb=>s.setParams({fadeDb})}/><NumberField label="Foliage loss · dB/m" value={p.foliageDbPerM??.045} min={0} max={1} step={.005} onChange={foliageDbPerM=>s.setParams({foliageDbPerM})}/><NumberField label="Canopy height · m" value={p.canopyM??15} min={0} max={50} onChange={canopyM=>s.setParams({canopyM})}/><NumberField label="Mesh RF edge limit" value={p.meshHops} min={1} max={7} onChange={meshHops=>s.setParams({meshHops})}/><NumberField label="Totem RF edge limit" value={p.totemHops} min={1} max={7} onChange={totemHops=>s.setParams({totemHops})}/></div><label className="check-field"><input type="checkbox" checked={p.clientsHop} onChange={e=>s.setParams({clientsHop:e.target.checked})}/>Clients may forward</label><label className="check-field"><input type="checkbox" checked={p.bagLoss} onChange={e=>s.setParams({bagLoss:e.target.checked})}/>Apply assumed 2.2 dB body/bag loss</label><label className="check-field"><input type="checkbox" checked={p.assumeUnknownHardware??false} onChange={e=>s.setParams({assumeUnknownHardware:e.target.checked})}/>Explore assumed Totem parameters</label><p className="muted">Totem specifications are unknown. Enabling assumptions produces a hypothetical estimate; it does not validate manufacturer range or proprietary mesh behavior.</p></Section>
 <Section title="Target area"><p className="muted">{polygon?'Custom target rectangle':'Default: inferred camp envelope with 30 m padding'}. Area is approximated by raster cell centers; unknown area remains in the denominator.</p><details><summary>Edit target rectangle · grid coordinates</summary><div className="field-grid">{(['west','east','north','south'] as const).map(key=><NumberField key={key} label={key} value={bounds[key]} min={0} max={key==='west'||key==='east'?COLS-1:ROWS-1} onChange={value=>setBounds(key,value)}/>)}</div><button onClick={()=>s.setParams({targetPolygon:undefined})}>Restore inferred camp envelope</button></details>{analysis&&<p className="muted">Target area: {(analysis.stats.targetAreaSqM/10000).toFixed(1)} ha · {percent(analysis.stats.meshUnknownFrac)} mesh unknown · {percent(analysis.stats.totemUnknownFrac)} Totem unknown</p>}</Section>
 <Section title="Coverage at exact camp points">{analysis?<><div className="stat-grid"><div><strong>{percent(analysis.stats.meshFrac)}</strong><span>Mesh target area served</span></div><div><strong>{percent(analysis.stats.totemFrac)}</strong><span>Totem target area served</span></div></div><div className="table-scroll"><table><thead><tr><th>Camp</th><th>Mesh</th><th>Totem</th></tr></thead><tbody>{analysis.pois.mesh.map((r,i)=><tr key={r.target.id}><th>{r.target.label}</th><td><Badge status={r.status}/><small>{margin(r.marginDb)}</small></td><td><Badge status={analysis.pois.totem[i].status}/></td></tr>)}</tbody></table></div><details><summary>Crew routes · {analysis.crewPairs.length} pairs</summary>{analysis.crewPairs.map(pair=><p key={`${pair.from}:${pair.to}`} className="route-detail">{s.nodes.find(n=>n.id===pair.from)?.label??pair.from} ↔ {s.nodes.find(n=>n.id===pair.to)?.label??pair.to}<br/><Badge status={pair.forward.status}/>{' / '}<Badge status={pair.reverse.status}/><small>{pair.forward.route.join(' → ')} · {margin(pair.forward.marginDb)}</small></p>)}</details></>:<p className="muted">Run a scenario to calculate exact point coverage.</p>}</Section>
 <Section title="Compare four options"><button className="primary-button" disabled={busy} onClick={onCompare}>Compare matched crew layouts</button><p className="muted">All four options use the same crew sites, target area and environmental assumptions. Preset layouts are illustrative.</p>{comparisons.length>0&&<div className="table-scroll"><table><thead><tr><th>Option</th><th>Mesh</th><th>Totem</th><th>Devices</th></tr></thead><tbody>{comparisons.map(c=><tr key={c.preset}><th>{presetLabels[c.preset]}</th><td>{percent(c.stats.meshFrac)}<small>{percent(c.stats.meshUnknownFrac)} unknown</small></td><td>{percent(c.stats.totemFrac)}<small>{percent(c.stats.totemUnknownFrac)} unknown</small></td><td>{c.stats.m1Count+c.stats.v4Count+c.stats.totemCount}</td></tr>)}</tbody></table></div>}</Section>
 </>}
 {tab==='placement'&&<><Section title="Find a better relay layout"><p>Maximize weighted camp reachability to the mesh base with both directions required.</p><p className="muted">Existing devices stay fixed. Candidates are inferred POI locations, with access, permission, power and mounting unverified. Exclude any unsuitable site before searching.</p><div className="field-grid"><NumberField label="Additional relay budget" value={budget} min={0} max={6} onChange={setBudget}/><label className="field"><span>Candidate antenna height</span><select value={height} onChange={e=>setHeight(Number(e.target.value))}><option value={3}>3 m above ground</option><option value={6}>6 m above ground</option></select></label></div><div className="candidate-list">{candidates.map(c=><label className="check-field" key={c.id}><input type="checkbox" checked={c.allowed} onChange={e=>setAllowed({...allowed,[c.siteId!]:e.target.checked})}/><span>{c.node.label}<small>Installation feasibility unknown</small></span></label>)}</div><button className="primary-button" disabled={busy||!mesh.length} onClick={()=>onOptimize(budget,candidates)}>Find best available layout</button></Section>{optimization&&<><Section title="Best found placement"><div className="stat-grid"><div><strong>+{optimization.best.gain.toFixed(1)}</strong><span>Weighted targets gained</span></div><div><strong>{optimization.best.candidateIds.length}</strong><span>Added relays</span></div></div><p>{optimization.method}</p><p className="muted">{optimization.evaluations} layouts evaluated · bottleneck {margin(optimization.best.bottleneckDb)}</p><button className="primary-button" disabled={busy} onClick={()=>s.replaceNodes(optimization.best.nodes)}>Apply best layout</button><p>Gained: {optimization.best.targetsGained.join(', ')||'No new targets'}</p><p>Remaining gaps: {optimization.best.gaps.join(', ')||'None in evaluated targets'}</p><p>Unknown: {optimization.best.unknown.join(', ')||'None in evaluated targets'}</p>{optimization.contributions.map(c=><p key={c.id}>{optimization.best.nodes.find(n=>n.id===c.id)?.label??c.id}: removing this relay loses {c.scoreLoss.toFixed(1)} weighted targets.</p>)}</Section><Section title="Alternative layouts">{optimization.alternatives.map((a,i)=><div className="alternative-card" key={i}><strong>Option {i+1} · +{a.gain.toFixed(1)} targets</strong><p>{a.candidateIds.length} added relays · {margin(a.bottleneckDb)}</p><button onClick={()=>s.replaceNodes(a.nodes)}>Apply option {i+1}</button></div>)}</Section><Section title="Search limits">{optimization.limitations.map(v=><p className="muted" key={v}>{v}</p>)}</Section></>}</>}
 {tab==='evidence'&&<><Section title="Model & source record"><p><strong>{MODEL_VERSION}</strong> · uncalibrated planning estimate</p>{MODEL_ASSUMPTIONS.map(v=><p className="muted" key={v}>{v}</p>)}<p><a href="https://www.itu.int/rec/R-REC-P.526/en" target="_blank" rel="noreferrer">ITU diffraction reference</a> · <a href="https://meshtastic.org/docs/configuration/radio/device/" target="_blank" rel="noreferrer">Meshtastic forwarding roles</a> · <a href="https://heltec.org/project/wifi-lora-32-v4/" target="_blank" rel="noreferrer">Heltec hardware variants</a></p><p className="muted">Land cover, occupied camp boundaries and installation sites are inferred. Field measurements and confirmed device settings are required before operational reliance.</p></Section><FieldNotebook nodes={s.nodes} params={p}/></>}
 </aside>;
}
