import { useEffect, useMemo, useRef, useState, type PointerEvent } from 'react';
import { Crosshair, Layers, Mountain, Minus, Plus } from 'lucide-react';
import { useSim } from '../lib/store';
import { COLS, ROWS, contourSegs, POIS, gridToLl, elevBilinear } from '../lib/terrain';
import { coverageColor,COVERAGE_GRADIENT } from '../lib/coverage-view';
import { SITE_AREAS, SITE_PATHS } from '../lib/site-features';
import { IMAGERY_VIEWS } from '../lib/imagery';
import { evaluateTarget, isFixed, isRouter, ROLE_LABELS, routeBetween, analysisSurface, KIND_META, targetPolygons, type SimParams, type Node, type Status, type Heat } from '../lib/radio';
import type { ValleyApi, ViewName, SceneState } from '../lib/valley-gl';

const COLORS:Record<Status,string>={likely:'#69b8ff',marginal:'#f2ba5b',unavailable:'#f47e76',unknown:'#b7c0cb'};
const WORDS:Record<Status,string>={likely:'Strong modeled link',marginal:'Weak / limited reserve',unavailable:'No two-way route',unknown:'Not enough information'};
const allPoints=SITE_AREAS.flatMap(a=>a.polygon);
const siteBounds=allPoints.length?{minX:Math.min(...allPoints.map(p=>p[0])),maxX:Math.max(...allPoints.map(p=>p[0])),minY:Math.min(...allPoints.map(p=>p[1])),maxY:Math.max(...allPoints.map(p=>p[1]))}:{minX:60,maxX:155,minY:45,maxY:150};
const siteCenter={x:(siteBounds.minX+siteBounds.maxX)/2,y:(siteBounds.minY+siteBounds.maxY)/2};
function eventCamera(width:number,height:number){const w=Math.max(siteBounds.maxX-siteBounds.minX,(siteBounds.maxY-siteBounds.minY)*width/height)*1.25,h=w*height/width;return {x:w>=COLS-1?(COLS-1)/2:Math.max(w/2,Math.min(COLS-1-w/2,siteCenter.x)),y:h>=ROWS-1?(ROWS-1)/2:Math.max(h/2,Math.min(ROWS-1-h/2,siteCenter.y)),width:w};}
type Gesture={kind:'pan'|'node';id?:string;startX:number;startY:number;x:number;y:number;cx:number;cy:number;moved:boolean};
export function ValleyMap({previewNodes,previewHeat,previewParams,editing,onEdit}:{previewNodes:Node[]|null;previewHeat:Heat|null;previewParams?:SimParams;editing:boolean;onEdit:()=>void}){
 const s=useSim(),svg=useRef<SVGSVGElement>(null),frame=useRef<HTMLElement>(null),host=useRef<HTMLDivElement>(null),api=useRef<ValleyApi|null>(null),gesture=useRef<Gesture|null>(null);
 const [mode,setMode]=useState<'plan'|'3d'>('3d'),[imagery,setImagery]=useState(IMAGERY_VIEWS.at(-1)!.id),[second,setSecond]=useState(IMAGERY_VIEWS[0].id);
 const [compare,setCompare]=useState(false),[swipe,setSwipe]=useState(50),[contours,setContours]=useState(true),[labels,setLabels]=useState(true),[zones,setZones]=useState(true);
 const [layerMenu,setLayerMenu]=useState(false),[handhelds,setHandhelds]=useState(true),[heights,setHeights]=useState(true),[routes,setRoutes]=useState(true),[coordinates,setCoordinates]=useState(true);const fitted=useRef(false);
 const [view,setView]=useState<ViewName>('south'),[fitKey,setFitKey]=useState(0),[moveId,setMoveId]=useState<string|null>(null),[opacity,setOpacity]=useState(.55),[coverageExtent,setCoverageExtent]=useState<'landscape'|'event'>('landscape'),[imageError,setImageError]=useState('');
 const [size,setSize]=useState({width:1000,height:700});
 const [camera,setCamera]=useState(()=>eventCamera(1000,700));
 const [cursor,setCursor]=useState<{x:number;y:number}|null>(null),[inspection,setInspection]=useState<{x:number;y:number;label?:string}|null>(null),[drag,setDrag]=useState<{id:string;x:number;y:number}|null>(null);
 const image=IMAGERY_VIEWS.find(i=>i.id===imagery)!,other=IMAGERY_VIEWS.find(i=>i.id===second)!;
 const height=camera.width*size.height/size.width,extent={x:camera.x-camera.width/2,y:camera.y-height/2,w:camera.width,h:height},unit=camera.width/size.width;
 const rawHeat=previewNodes?previewHeat:s.heat,visibleHeat=useMemo(()=>rawHeat&&coverageExtent==='event'?{...rawHeat,scope:'event' as const}:rawHeat,[rawHeat,coverageExtent]);const effectiveNodes=previewNodes??s.nodes;
 const paramKey=JSON.stringify(previewParams??s.params()),params=useMemo<SimParams>(()=>JSON.parse(paramKey),[paramKey]);
 const contourPath=useMemo(()=>{if(!contours)return {major:'',minor:''};const c=contourSegs();return {major:segments(c.major),minor:segments(c.minor)};},[contours]);
 const visibleNodes=useMemo(()=>effectiveNodes.filter(n=>editing||handhelds||isFixed(n)),[effectiveNodes,editing,handhelds]);
 const selected=effectiveNodes.find(n=>n.id===s.selected),system='mesh' as const;
 const inspected=useMemo(()=>inspection?evaluateTarget({id:'inspection',label:inspection.label??'Selected location',...inspection},effectiveNodes,params,analysisSurface,system):null,[inspection,effectiveNodes,params,system]);
 const selectedRoutes=useMemo(()=>{if(!selected)return null;const base=params.meshRootId??s.nodes[0]?.id??'';return {forward:routeBetween(effectiveNodes,selected.id,base,params,analysisSurface),reverse:routeBetween(effectiveNodes,base,selected.id,params,analysisSurface)};},[selected,s.nodes,effectiveNodes,params]);
 const shownRoutes=inspected??selectedRoutes;
 const routeLines=useMemo(()=>{const lines:Array<{a:{x:number;y:number};b:{x:number;y:number};status:Status}>=[];if(!routes)return lines;const records=shownRoutes?[shownRoutes.forward,shownRoutes.reverse]:effectiveNodes.filter(n=>n.id!==params.meshRootId).flatMap(n=>[routeBetween(effectiveNodes,n.id,params.meshRootId??'',params,analysisSurface),routeBetween(effectiveNodes,params.meshRootId??'',n.id,params,analysisSurface)]);for(const r of records)for(let i=1;i<r.route.length;i++){const a=effectiveNodes.find(n=>n.id===r.route[i-1])??inspection,b=effectiveNodes.find(n=>n.id===r.route[i])??inspection;if(a&&b&&!lines.some(l=>(l.a===a&&l.b===b)||(l.a===b&&l.b===a)))lines.push({a,b,status:r.status});}return lines;},[routes,shownRoutes,effectiveNodes,inspection,params]);
 const inspectPoint=(p:{x:number;y:number;label?:string})=>{if(moveId&&!previewNodes){s.moveNode(moveId,p.x,p.y);setMoveId(null);s.select(moveId);return;}s.select(null);setInspection(p);};
 const sceneState=useRef<SceneState>(null!);sceneState.current={nodes:visibleNodes,params,heat:visibleHeat,overlay:s.overlay,imagery:image.url,view,opacity,layers:{labels,heights,zones,routes,contours,coordinates},routeLines,selectedId:s.selected,focus:s.focusPoint,fitKey,onSelect:id=>{s.select(id);setInspection(null);},onInspect:inspectPoint,onCursor:setCursor};
 useEffect(()=>{if(!frame.current)return;const obs=new ResizeObserver(entries=>{const r=entries[0].contentRect;setSize({width:Math.max(r.width,1),height:Math.max(r.height,1)});if(!fitted.current&&r.width&&r.height){fitted.current=true;setCamera(eventCamera(r.width,r.height));}});obs.observe(frame.current);return()=>obs.disconnect();},[]);
 useEffect(()=>{if(!editing)setInspection(null);},[editing]);
 useEffect(()=>{if(!s.focusPoint)return;setInspection(s.focusPoint);setCamera(c=>({...c,x:s.focusPoint!.x,y:s.focusPoint!.y}));},[s.focusPoint]);
 useEffect(()=>{if(!selected)return;setInspection(null);setCamera(c=>Math.abs(selected.x-c.x)>c.width*.43||Math.abs(selected.y-c.y)>c.width*size.height/size.width*.43?{...c,x:selected.x,y:selected.y}:c);},[selected,size.height,size.width]);
 useEffect(()=>{if(mode!=='3d'||!host.current)return;const el=host.current;let disposed=false;const fail=()=>{if(disposed)return;setMode('plan');setImageError('3D is unavailable here. The plan map remains usable.');};const imageFail=()=>setImageError('Imagery could not load. Select another source.');el.addEventListener('webgl-failed',fail);el.addEventListener('imagery-error',imageFail);import('../lib/valley-gl').then(({mountValley})=>{if(!disposed)api.current=mountValley(el,sceneState.current);}).catch(fail);return()=>{disposed=true;el.removeEventListener('webgl-failed',fail);el.removeEventListener('imagery-error',imageFail);api.current?.destroy();api.current=null;};},[mode]);
 useEffect(()=>{api.current?.update(sceneState.current);});
 const locate=(e:PointerEvent)=>{const el=svg.current;if(!el)return null;const pt=el.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const matrix=el.getScreenCTM();if(!matrix)return null;const p=pt.matrixTransform(matrix.inverse());return {x:Math.max(0,Math.min(COLS-1,p.x)),y:Math.max(0,Math.min(ROWS-1,p.y))};};
 const onDown=(e:PointerEvent<SVGSVGElement>)=>{if(e.button!==0)return;gesture.current={kind:'pan',startX:e.clientX,startY:e.clientY,x:0,y:0,cx:camera.x,cy:camera.y,moved:false};e.currentTarget.setPointerCapture(e.pointerId);};
 const onMove=(e:PointerEvent<SVGSVGElement>)=>{const p=locate(e);setCursor(p);const g=gesture.current;if(!g)return;const dx=e.clientX-g.startX,dy=e.clientY-g.startY;if(Math.hypot(dx,dy)>4)g.moved=true;if(g.kind==='node')setDrag({id:g.id!,x:Math.max(0,Math.min(COLS-1,g.x+dx*unit)),y:Math.max(0,Math.min(ROWS-1,g.y+dy*unit))});else if(g.moved)setCamera(c=>({...c,x:Math.max(0,Math.min(COLS-1,g.cx-dx*unit)),y:Math.max(0,Math.min(ROWS-1,g.cy-dy*unit))}));};
 const onUp=(e:PointerEvent<SVGSVGElement>)=>{const g=gesture.current;gesture.current=null;if(g?.kind==='node'){if(g.moved&&drag)s.moveNode(g.id!,drag.x,drag.y);setDrag(null);return;}if(g?.moved)return;const p=locate(e);if(!p)return;if(editing&&s.tool!=='select'&&s.tool!=='erase'){s.addNode(s.tool,p.x,p.y);setInspection(null);}else inspectPoint(p);};
 const fit=(full=false)=>{setFitKey(k=>k+1);setCamera(full?{x:(COLS-1)/2,y:(ROWS-1)/2,width:Math.max(COLS-1,(ROWS-1)*size.width/size.height)*1.03}:eventCamera(size.width,size.height));};
 const routeNames=(ids:string[])=>ids.map(id=>effectiveNodes.find(n=>n.id===id)?.label??'Receiver').join(' → ')||'No route';
 const ll=cursor?gridToLl(cursor.x,cursor.y):null;
 const proposals:Node[]=[];
 const markerOffset=(n:Node,index:number)=>{const count=effectiveNodes.slice(0,index).filter(other=>visibleNodes.some(v=>v.id===other.id)&&Math.hypot(other.x-n.x,other.y-n.y)<.01).length;return count?{x:(count%2?1:-1)*42,y:-30*Math.ceil(count/2)}:{x:0,y:0};};
 return <section ref={frame} className="map-frame" data-view={mode} data-preview={Boolean(previewNodes)} aria-label="Property coverage map">
  <div className="map-toolbar"><button aria-expanded={layerMenu} aria-controls="map-layers" onClick={()=>setLayerMenu(!layerMenu)}><Layers size={15}/>Layers</button><button onClick={()=>setMode(mode==='3d'?'plan':'3d')}>{mode==='3d'?'2D map':'3D terrain'}</button><button onClick={()=>fit()}>Fit event grounds</button></div>
  {layerMenu&&<div className="layer-menu" id="map-layers" aria-label="Map layers"><div className="layer-menu-heading"><strong>Choose your detail</strong><button aria-label="Close layers" onClick={()=>setLayerMenu(false)}>×</button></div><p>Fixed infrastructure stays visible.</p><label><input type="checkbox" checked={handhelds} onChange={e=>setHandhelds(e.target.checked)}/>Roaming test positions{editing&&<small>All shown while customizing</small>}</label>{<><label><input type="checkbox" checked={labels} onChange={e=>setLabels(e.target.checked)}/>Place names</label><label><input type="checkbox" checked={heights} onChange={e=>setHeights(e.target.checked)}/>Antenna heights</label><label><input type="checkbox" checked={zones} onChange={e=>setZones(e.target.checked)}/>Event areas and roads</label><label><input type="checkbox" checked={routes} onChange={e=>setRoutes(e.target.checked)}/>Network routes</label><label><input type="checkbox" checked={contours} onChange={e=>setContours(e.target.checked)}/>Contours</label><label><input type="checkbox" checked={coordinates} onChange={e=>setCoordinates(e.target.checked)}/>Coordinates</label></>}<label className="layer-select">Coverage<select aria-label="Coverage overlay" value={s.overlay} onChange={e=>s.setOverlay(e.target.value as typeof s.overlay)}><option value="none">Hidden</option><option value="mesh">Signal heatmap</option></select></label><label className="layer-select">Coverage extent<select aria-label="Coverage extent" value={coverageExtent} onChange={e=>setCoverageExtent(e.target.value as typeof coverageExtent)}><option value="landscape">Whole landscape</option><option value="event">Event areas only</option></select></label><label>Heatmap opacity<input aria-label="Heatmap opacity" type="range" min=".15" max=".9" step=".05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label><details className="imagery-options"><summary>Imagery and terrain</summary><select aria-label="Imagery source" value={imagery} onChange={e=>{setImagery(e.target.value);if(second===e.target.value)setSecond(IMAGERY_VIEWS.find(i=>i.id!==e.target.value)!.id);setImageError('');}}>{IMAGERY_VIEWS.map(i=><option key={i.id} value={i.id}>{i.label}</option>)}</select><div className="segmented"><button className={mode==='plan'?'active':''} onClick={()=>setMode('plan')}>Plan</button><button className={mode==='3d'?'active':''} onClick={()=>setMode('3d')}><Mountain size={14}/>3D terrain</button></div>{mode==='plan'&&<button aria-pressed={compare} onClick={()=>setCompare(!compare)}>Compare imagery</button>}</details></div>}

  {compare&&mode==='plan'&&<div className="compare-bar"><span>Same terrain · different acquisition</span><select aria-label="Comparison imagery" value={second} onChange={e=>setSecond(e.target.value)}>{IMAGERY_VIEWS.filter(i=>i.id!==imagery).map(i=><option key={i.id} value={i.id}>{i.label}</option>)}</select><input aria-label="Imagery comparison position" type="range" min="0" max="100" value={swipe} onChange={e=>setSwipe(+e.target.value)}/></div>}
  {mode==='3d'?<><div ref={host} className="three-host"/><div className="angle-bar">{(['north','east','south','west','top'] as ViewName[]).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v}</button>)}<span className="actual-relief">Actual terrain · 1×</span></div><p className="three-hint">Drag to orbit · scroll to zoom · select a radio or landscape point</p></>:<svg ref={svg} className="plan-svg" viewBox={`${extent.x} ${extent.y} ${extent.w} ${extent.h}`} aria-label="Registered satellite terrain and network" onPointerDown={onDown} onPointerMove={onMove} onPointerUp={onUp} onPointerCancel={()=>{gesture.current=null;setDrag(null);}}>
   <defs><clipPath id="coverage-targets">{(visibleHeat?.scope==='landscape'?[[[0,0],[COLS-1,0],[COLS-1,ROWS-1],[0,ROWS-1]]]:targetPolygons(params)).map((polygon,i)=><polygon key={i} points={polygon.map(p=>p.join(',')).join(' ')}/>)}</clipPath><pattern id="unknown-coverage" width="1" height="1" patternUnits="userSpaceOnUse"><path d="M0 0L1 1" stroke="#dfe5ed" strokeWidth=".12"/></pattern><clipPath id="image-swipe"><rect x={extent.x} y="0" width={extent.w*swipe/100} height={ROWS-1}/></clipPath></defs>
   <rect width={COLS-1} height={ROWS-1} fill="#26303a"/><image href={image.url} width={COLS-1} height={ROWS-1} preserveAspectRatio="none" onError={()=>setImageError('Imagery could not load. Select another source.')}/>
   {compare&&<image href={other.url} width={COLS-1} height={ROWS-1} preserveAspectRatio="none" clipPath="url(#image-swipe)"/>}
   {contours&&<g className="terrain-contours" fill="none" stroke="#ffffff" pointerEvents="none"><path d={contourPath.minor} strokeWidth=".1" opacity=".15"/><path d={contourPath.major} strokeWidth=".2" opacity=".5"/></g>}
   {zones&&<g className="event-zones" pointerEvents="none">{SITE_PATHS.map(p=><polyline key={p.id} points={p.points.map(v=>v.join(',')).join(' ')} fill="none" stroke={p.kind==='creek'?'#91cff0':'#faf4de'} strokeWidth={p.kind==='creek'?1.5:1.1} vectorEffect="non-scaling-stroke" opacity=".7" strokeDasharray={p.kind==='creek'?undefined:'5 4'}/>)}{SITE_AREAS.map(a=><polygon key={a.id} points={a.polygon.map(p=>p.join(',')).join(' ')} fill="none" stroke="#ffefbb" strokeWidth="1.2" strokeDasharray="5 4" vectorEffect="non-scaling-stroke" opacity=".8"/>)}</g>}
   {visibleHeat&&s.overlay!=='none'&&<g className="coverage-heatmap" clipPath="url(#coverage-targets)" opacity={opacity} pointerEvents="none">{Array.from({length:visibleHeat.w*visibleHeat.h},(_,k)=>{const h=visibleHeat!;if(!h.targetWeights[k]&&h.scope!=='landscape')return null;const value=h.mesh[k],x=(k%h.w)*h.step,y=Math.floor(k/h.w)*h.step;return <g key={k} className="coverage-cell" data-margin={h.meshMargin[k]} data-relay={Boolean(h.meshViaRelay[k])}><rect x={x} y={y} width={Math.min(h.step,COLS-1-x)} height={Math.min(h.step,ROWS-1-y)} fill={coverageColor(value,h.meshMargin[k])}/>{value<0&&<rect x={x} y={y} width={h.step} height={h.step} fill="url(#unknown-coverage)"/>}</g>;})}</g>}
   {zones&&params.targetPolygon&&<polygon points={params.targetPolygon.map(p=>p.join(',')).join(' ')} fill="none" stroke="#83c0ff" strokeWidth="2" strokeDasharray="7 4" vectorEffect="non-scaling-stroke" pointerEvents="none"/>}
   <g className="network-routes" pointerEvents="none">{routeLines.map((l,i)=><line key={i} x1={l.a.x} y1={l.a.y} x2={l.b.x} y2={l.b.y} stroke={COLORS[l.status]} strokeWidth="3" vectorEffect="non-scaling-stroke" strokeDasharray="6 4"/>)}</g>
   {labels&&POIS.filter(p=>p.kind==='camp'||p.kind==='gate'||p.kind==='stage'||p.kind==='amenity').map(p=><g key={p.id} role="button" tabIndex={0} aria-label={`Inspect ${p.label}`} className="site-label" transform={`translate(${p.x} ${p.y}) scale(${unit})`} onPointerDown={e=>e.stopPropagation()} onPointerUp={e=>{e.stopPropagation();s.select(null);setInspection({x:p.x,y:p.y,label:(p as {label?:string}).label});}} onKeyDown={e=>{if(e.key==='Enter'){s.select(null);setInspection({x:p.x,y:p.y,label:(p as {label?:string}).label});}}}><circle r="3" fill="#fff5d5" stroke="#172331" strokeWidth="1.5"/><text x="7" y="-6" fontSize="11" fontWeight="600" fill="#fff6df" stroke="#1b2530" strokeWidth="3" paintOrder="stroke">{p.label}</text></g>)}
   {proposals.map((n,i)=>{const offset=s.nodes.some(old=>Math.hypot(old.x-n.x,old.y-n.y)<40*unit)?{x:48,y:-34}:{x:0,y:0};return <g key={n.id} transform={`translate(${n.x} ${n.y}) scale(${unit})`} pointerEvents="none"><line x2={offset.x} y2={offset.y} stroke="#ffe3a0" strokeDasharray="3 3"/><g transform={`translate(${offset.x} ${offset.y})`}><circle r="18" fill="#182b40" fillOpacity=".9" stroke="#ffe3a0" strokeWidth="2" strokeDasharray="5 3"/><text textAnchor="middle" y="4" fontSize="11" fill="#fff4d6" fontWeight="700">R{i+1}</text><text textAnchor="middle" y={offset.x?-25:31} fontSize="12" fill="#fff3d4" stroke="#1b2530" strokeWidth="3" paintOrder="stroke">{n.agl??3} m proposed</text></g></g>;})}
   {effectiveNodes.map((n,i)=>{if(!visibleNodes.some(v=>v.id===n.id))return null;const p=drag?.id===n.id?drag:n,offset=markerOffset(n,i),router=isRouter(n),base=n.id==='primary-p1',site=POIS.find(v=>Math.hypot(v.x-n.x,v.y-n.y)<2),marker=router?`R${effectiveNodes.filter(isRouter).indexOf(n)+1}`:isFixed(n)?`C${effectiveNodes.filter(v=>isFixed(v)&&!isRouter(v)).indexOf(n)+1}`:'H',caption=base?'P1 solar':isFixed(n)?ROLE_LABELS[n.role??'client']:null;return <g key={n.id} role="button" aria-label={`Select ${n.label}`} tabIndex={0} className="map-node" data-node-id={n.id} data-role={router?'router':isFixed(n)?'fixed-client':'handheld'} data-agl={n.agl??KIND_META[n.kind].agl} transform={`translate(${p.x} ${p.y}) scale(${unit})`} onPointerDown={e=>{e.stopPropagation();if(editing&&s.tool==='erase'){s.removeNode(n.id);return;}s.select(n.id);if(!editing||previewNodes)return;gesture.current={kind:'node',id:n.id,startX:e.clientX,startY:e.clientY,x:n.x,y:n.y,cx:camera.x,cy:camera.y,moved:false};svg.current?.setPointerCapture(e.pointerId);setDrag({id:n.id,x:n.x,y:n.y});}} onPointerUp={e=>{if(!editing)e.stopPropagation();}} onKeyDown={e=>{if(e.key==='Enter')s.select(n.id);if(e.key==='Delete'&&editing&&!previewNodes)s.removeNode(n.id);const dirs:Record<string,[number,number]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(editing&&!previewNodes&&dirs[e.key]){e.preventDefault();const step=e.shiftKey?.1:1;s.moveNode(n.id,n.x+dirs[e.key][0]*step,n.y+dirs[e.key][1]*step);}}}>
    <line x2={offset.x} y2={offset.y} stroke="#ffd07b" strokeDasharray="3 3"/><g transform={`translate(${offset.x} ${offset.y})`}>
    {router?<rect x="-12" y="-12" width="24" height="24" rx="5" fill={s.selected===n.id?'#f4bd68':'#202c3d'} stroke="#ffd07b" strokeWidth={s.selected===n.id?3:2}/>:<circle r="12" fill={s.selected===n.id?'#70b7ff':'#182b40'} stroke="#94c8ff" strokeWidth={s.selected===n.id?3:2}/>}
    <text textAnchor="middle" y="4" fontSize="11" fill={s.selected===n.id?'#102036':'#fff'} fontWeight="700">{marker}</text>{caption&&<text className="infrastructure-label" textAnchor="middle" y={offset.x?-24:29} fontSize="12" fill="#fff" stroke="#152231" strokeWidth="4" paintOrder="stroke">{caption}{site?` · ${site.label.replace(/ camp$/i,'')}`:''}</text>}{heights&&<text className="antenna-caption" textAnchor="middle" y={offset.x?-42:caption?45:28} fontSize="11" fill="#fff" stroke="#152231" strokeWidth="3" paintOrder="stroke">{n.agl??KIND_META[n.kind].agl} m</text>}
   </g></g>;})}
   {inspection&&<circle cx={inspection.x} cy={inspection.y} r={10*unit} fill="none" stroke="#fff" strokeWidth="2" vectorEffect="non-scaling-stroke"/>}
   {compare&&<line x1={extent.x+extent.w*swipe/100} x2={extent.x+extent.w*swipe/100} y1="0" y2={ROWS-1} stroke="#fff" strokeWidth="2" vectorEffect="non-scaling-stroke"/>}
  </svg>}
  {<div className="map-floating-left"><div className="north-mark" aria-hidden={mode==='3d'} style={{visibility:mode==='3d'?'hidden':undefined}}>↑<small>N</small></div><div className="zoom-controls"><button aria-label="Zoom in" onClick={()=>mode==='3d'?api.current?.zoom(1/1.3):setCamera(c=>({...c,width:Math.max(20,c.width/1.3)}))}><Plus size={16}/></button><button aria-label="Zoom out" onClick={()=>mode==='3d'?api.current?.zoom(1.3):setCamera(c=>({...c,width:Math.min(420,c.width*1.3)}))}><Minus size={16}/></button><button aria-label="Fit property" onClick={()=>fit(true)}><Crosshair size={16}/></button></div></div>}

  {(inspected||selected)&&<div className="map-inspection"><button className="close" aria-label="Close inspection" onClick={()=>{setInspection(null);s.select(null);}}>×</button><small>{previewNodes?'PREVIEW · ':''}{selected?'DEVICE '+(effectiveNodes.indexOf(selected)+1):'RECEIVER LOCATION'}</small><strong>{selected?.label??inspected?.target.label}</strong>{selected&&<span>{KIND_META[selected.kind].title} · {ROLE_LABELS[selected.role??'client']} · {isFixed(selected)?'Fixed infrastructure':'Roaming test point'} · {selected.agl??KIND_META[selected.kind].agl} m above ground · {elevBilinear(selected.x,selected.y).toFixed(0)} m elevation</span>}{inspected&&<><strong style={{color:COLORS[inspected.status]}}>{WORDS[inspected.status]}</strong><span>{Number.isFinite(inspected.marginDb)?`${inspected.marginDb.toFixed(1)} dB remaining margin · `:''}{params.receiverAgl??1.5} m receiver</span></>}{shownRoutes&&routes&&<><span>Out: {routeNames(shownRoutes.forward.route)}</span><span>Return: {routeNames(shownRoutes.reverse.route)}</span></>}{selected&&!previewNodes&&<div className="button-row"><button onClick={onEdit}>Edit radio settings</button><button onClick={()=>{setMoveId(selected.id);setInspection(null);}}>Move this radio</button></div>}{inspection&&editing&&!previewNodes&&<div className="button-row"><span>Choose a fixed radio to move it here; add radios through Equipment.</span><button onClick={()=>{s.addNode('l1',inspection.x,inspection.y);setInspection(null);}}>Add roaming test point</button></div>}</div>}
  {moveId&&<div className="move-instruction" role="status">Click the landscape to place {s.nodes.find(n=>n.id===moveId)?.label}. This locks its new position.<button onClick={()=>setMoveId(null)}>Cancel move</button></div>}
  {proposals.length>0&&<div className="placement-delta">Dashed markers preview {proposals.length} proposed relays at their recommended heights. Apply from the placement panel.</div>}
  <div className="heatmap-key"><div><strong>{previewNodes?'Scenario coverage':'Applied network coverage'}</strong><span>Two-way signal margin · 40 m model cells</span></div>{s.overlay==='mesh'?<><div className="margin-gradient" style={{background:COVERAGE_GRADIENT}}/><div className="margin-ticks"><span style={{left:0}}>0</span><span style={{left:'10%'}}>6</span><span style={{left:'40%'}}>24</span><span style={{left:'66.667%'}}>40</span><span style={{right:0}}>60+ dB</span></div><p><i className="key-no-route"/>No route <i className="key-unknown"/>Unknown · strong ≥6 dB; dashed links are routes, not line of sight</p></>:<p>Heatmap hidden · enable it in Layers.</p>}</div>
  {imageError&&<div className="map-error">{imageError}</div>}
  <div className="map-footer"><span>{image.attribution} · {image.date}{compare&&mode==='plan'?` / ${other.date}`:''}</span><span>{coordinates&&(ll?`${ll[0].toFixed(5)}, ${ll[1].toFixed(5)}`:'Coordinates · move over terrain')}{mode==='plan'&&<span className="map-scale"><i style={{width:`${10/camera.width*size.width}px`}}/>100 m</span>}</span></div>
 </section>;
}
function segments(values:number[]){let d='';for(let i=0;i<values.length;i+=4)d+=`M${values[i]} ${values[i+1]}L${values[i+2]} ${values[i+3]}`;return d;}
