import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { hostname, platform } from 'node:os';
import { resolve } from 'node:path';
import { createServer } from 'node:net';
if (platform() === 'darwin') throw new Error('Browser acceptance must run on z370 or an approved remote runner.');
const runId=process.env.RIDGEMESH_RUN_ID;
const revision=process.env.RIDGEMESH_REVISION;
if(!runId||!revision)throw new Error('RIDGEMESH_RUN_ID and RIDGEMESH_REVISION are required.');
const out=resolve('artifacts',runId);mkdirSync(out,{recursive:true});
const port=await new Promise((resolve,reject)=>{const listener=createServer();listener.on('error',reject);listener.listen(0,'127.0.0.1',()=>{const assigned=listener.address().port;listener.close(()=>resolve(assigned));});});
const base=process.env.RIDGEMESH_BROWSER_URL||`http://127.0.0.1:${port}`;
const report={host:hostname(),runId,revision,url:base,started:new Date().toISOString(),checks:[],errors:[],failedRequests:[],workers:[],imagery:[],screenshots:[],metrics:[]};
console.log(`RAN ON ${hostname()} · run ${runId} · revision ${revision} · URL ${base}`);
let server,browser;let serverLog='';
const deadline=setTimeout(()=>{console.error('Browser check exceeded 150 seconds');cleanup();process.exit(124);},150000);
function cleanup(){if(server?.pid){try{process.kill(-server.pid,'SIGTERM');}catch{/* already stopped */}}}
process.on('SIGTERM',()=>{cleanup();process.exit(143);});process.on('SIGINT',()=>{cleanup();process.exit(130);});
const check=(name)=>{report.checks.push(name);console.log(`PASS ${name}`);};
try{
 if(!process.env.RIDGEMESH_BROWSER_URL){server=spawn(process.execPath,['node_modules/vite/bin/vite.js','dev','--host','127.0.0.1','--port',String(port),'--strictPort'],{detached:true,stdio:['ignore','pipe','pipe']});server.stdout.on('data',b=>{serverLog+=b;});server.stderr.on('data',b=>{serverLog+=b;});}
 let ready=false;for(let i=0;i<60;i++){if(server?.exitCode!==null&&server?.exitCode!==undefined)throw new Error(`App server exited: ${serverLog}`);try{const r=await fetch(base);if(r.ok){ready=true;break;}}catch{/* bounded startup */}await new Promise(r=>setTimeout(r,500));}assert.ok(ready,'App server did not become ready');
 browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await context.addInitScript(()=>{window.__ridgemeshWorkerRuns=[];window.__ridgemeshFeedback=[];document.addEventListener('click',event=>{if(event.target.closest?.('[aria-label="Zoom in"]')){const start=performance.now();requestAnimationFrame(()=>requestAnimationFrame(()=>window.__ridgemeshFeedback.push(performance.now()-start)));}},true);const NativeWorker=window.Worker;window.Worker=class extends NativeWorker{constructor(...args){super(...args);const started=performance.now();this.addEventListener('message',event=>{if(event.data.kind!=='progress')window.__ridgemeshWorkerRuns.push({kind:event.data.kind,workerReportedMs:event.data.elapsed,creationToResultMs:performance.now()-started});});}};});const page=await context.newPage();page.setDefaultTimeout(15000);
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));page.on('worker',w=>report.workers.push(w.url()));page.on('response',r=>{if(r.url().includes('/imagery/'))report.imagery.push({url:r.url(),status:r.status()});});
 await page.goto(base,{waitUntil:'networkidle'});await page.getByRole('link',{name:'RidgeMesh home'}).waitFor();check('RidgeMesh route rendered');const analysisStart=Date.now();await page.getByText('Current scenario calculated',{exact:true}).waitFor({timeout:60000});report.metrics.push({initialAnalysisWaitMs:Date.now()-analysisStart});report.metrics.push({initialWorkerRuns:await page.evaluate(()=>window.__ridgemeshWorkerRuns)});check('Current scenario completed in worker');
 const scenarioEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export',exact:true}).click();const scenarioDownload=await scenarioEvent;const scenarioPath=resolve(out,'scenario-export.json');await scenarioDownload.saveAs(scenarioPath);const exported=JSON.parse(readFileSync(scenarioPath,'utf8'));const imported={...exported,name:'Browser roundtrip scenario'};await page.getByLabel('Import scenario file').setInputFiles({name:'scenario.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await page.waitForFunction(()=>JSON.parse(localStorage.getItem('ridgemesh-scenario-v1')||'{}').name==='Browser roundtrip scenario');assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('ridgemesh-scenario-v1'))),imported);check('Scenario export/import preserves complete snapshot');
 const source=page.getByRole('combobox',{name:'Imagery source',exact:true});assert.equal(await source.locator('option').count(),3);const sources=await source.locator('option').evaluateAll(options=>options.map(o=>o.value));
 for(const value of sources){await source.selectOption(value);await page.waitForTimeout(200);}check('Three imagery acquisitions selectable');
 await page.getByRole('button',{name:'Compare imagery',exact:true}).click();await page.getByRole('combobox',{name:'Comparison imagery'}).waitFor();await page.getByRole('slider',{name:'Imagery comparison position'}).fill('35');assert.equal(await page.getByRole('slider',{name:'Imagery comparison position'}).inputValue(),'35');check('Synchronized imagery comparison slider works');
 const opacity=page.getByRole('slider',{name:'Coverage opacity'});await opacity.fill('0.5');await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByRole('button',{name:'Fit property',exact:true}).click();check('Plan opacity and zoom controls work');
 const map=page.getByRole('region',{name:'Property coverage map'});await map.screenshot({path:resolve(out,'desktop-map-raw.png')});report.screenshots.push('desktop-map-raw.png');
 await page.getByRole('button',{name:'3D terrain',exact:true}).click();await page.locator('.three-host canvas').waitFor({state:'visible'});await page.getByRole('button',{name:'north',exact:true}).click();await page.getByRole('combobox',{name:'Vertical exaggeration'}).selectOption('1');check('WebGL terrain and cardinal camera controls work');
 if(process.env.RIDGEMESH_RENDERER_DIAGNOSTICS==='1'){
  const canvas=page.locator('.three-host canvas');await page.waitForFunction(()=>document.querySelector('.three-host canvas')?.dataset.geometries!==undefined);
  for(const [view,height,preset] of [['north','1','m1-only'],['east','2','backbone'],['south','1','m1-only'],['west','2','backbone'],['north','1','m1-only'],['east','2','backbone']]){await page.getByRole('button',{name:view,exact:true}).click();await page.getByRole('combobox',{name:'Vertical exaggeration'}).selectOption(height);const before=await page.evaluate(()=>window.__ridgemeshWorkerRuns.length);await page.getByLabel('Starting layout').selectOption(preset);await page.waitForFunction(count=>window.__ridgemeshWorkerRuns.length>count,before,{timeout:60000});await page.waitForTimeout(100);report.metrics.push({rendererCycle:preset,...await canvas.evaluate(c=>({geometries:Number(c.dataset.geometries),textures:Number(c.dataset.textures)}))});}
  const cycles=report.metrics.filter(m=>m.rendererCycle);for(const preset of ['m1-only','backbone']){const samples=cycles.filter(c=>c.rendererCycle===preset);assert.equal(samples[1].geometries,samples[2].geometries,`${preset} geometry count grows after warmup`);assert.equal(samples[1].textures,samples[2].textures,`${preset} texture count grows after warmup`);}check('Renderer geometry/texture counts plateau across six bounded preset/height/view changes');
 }

 await page.waitForTimeout(500);await map.screenshot({path:resolve(out,'terrain-3d-raw.png')});report.screenshots.push('terrain-3d-raw.png');
 await page.getByRole('button',{name:'Plan',exact:true}).click();
 // Five bounded user interactions characterize DOM stability, not a load benchmark.
 for(let i=0;i<5;i++){const t=Date.now();await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByRole('button',{name:'Fit property',exact:true}).click();report.metrics.push({iteration:i,inputRoundtripMs:Date.now()-t,...await page.evaluate(()=>({domNodes:document.querySelectorAll('*').length,canvasCount:document.querySelectorAll('canvas').length,resourceCount:performance.getEntriesByType('resource').length}))});}
 report.metrics.push({zoomClickToTwoAnimationFramesMs:await page.evaluate(()=>window.__ridgemeshFeedback)});
 if(process.env.RIDGEMESH_EXTENDED_BROWSER==='1'){
  await page.getByRole('region',{name:'Direct radio path inspector'}).waitFor();await page.getByRole('img',{name:/Terrain profile over/}).waitFor();check('Direct path profile and Fresnel chart rendered');
  await page.getByRole('button',{name:'Compare matched crew layouts'}).click();await page.getByRole('button',{name:'Cancel calculation'}).click();await page.getByText('Calculation cancelled',{exact:true}).waitFor();check('Comparison cancellation is explicit');
  await page.getByRole('button',{name:'Compare matched crew layouts'}).click();await page.locator('.table-scroll tbody tr').nth(3).waitFor({timeout:60000});check('Four matched comparison options complete');
  await page.getByRole('tab',{name:'Placement',exact:true}).click();await page.getByLabel('Additional relay budget').fill('1');await page.getByRole('button',{name:'Find best available layout'}).click();await page.getByRole('heading',{name:'Best found placement',exact:true}).waitFor({timeout:60000});check('Constrained one-relay optimizer returns best found layout');
  await page.getByRole('tab',{name:'Network',exact:true}).click();await page.getByLabel('Starting layout').selectOption('empty');await page.getByRole('heading',{name:'Devices · 0',exact:true}).waitFor();await page.getByLabel('Starting layout').selectOption('backbone');await page.getByLabel('Starting layout').selectOption('totem-crew');await page.getByLabel('Starting layout').selectOption('m1-only');await page.getByText('Current scenario calculated',{exact:true}).waitFor({timeout:60000});const latest=await page.evaluate(()=>JSON.parse(localStorage.getItem('ridgemesh-scenario-v1')));assert.equal(latest.name,'m1-only');assert.ok(latest.nodes.every(n=>n.kind==='m1'));check('Empty and rapidly superseded presets settle on latest scenario');

  await page.getByRole('tab',{name:'Evidence',exact:true}).click();await page.getByRole('region',{name:'Field notebook'}).waitFor();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export observations',exact:true}).click();assert.equal((await download).suggestedFilename(),'ridgemesh-field-log.json');
  await page.getByRole('textbox',{name:'Observation JSON'}).fill(JSON.stringify({schema:'ridgemesh-field-log/1',observations:[]}));await page.getByRole('button',{name:'Validate and import',exact:true}).click();assert.ok(await page.evaluate(()=>localStorage.getItem('ridgemesh-field-observations-v1')));await page.reload({waitUntil:'networkidle'});assert.ok(await page.evaluate(()=>localStorage.getItem('ridgemesh-field-observations-v1')));check('Field JSON export/import persists across reload');
 }
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Plan',exact:true}).click();await map.screenshot({path:resolve(out,'mobile-map-raw.png')});report.screenshots.push('mobile-map-raw.png');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Mobile page horizontally overflows');check('Mobile plan fits viewport');
 assert.ok(new Set(report.imagery.filter(r=>r.status===200).map(r=>r.url)).size>=3,'Not all three imagery acquisitions loaded successfully');assert.ok(report.workers.length,'No worker started');assert.equal(report.errors.length,0,JSON.stringify(report.errors));check('Imagery and worker loaded without browser console errors');
 report.status='passed';
}catch(error){report.status='failed';report.failure=error.stack||String(error);console.error(report.failure);process.exitCode=1;}finally{clearTimeout(deadline);await browser?.close();cleanup();report.finished=new Date().toISOString();writeFileSync(resolve(out,'browser-report.json'),JSON.stringify(report,null,2));writeFileSync(resolve(out,'server.log'),serverLog);console.log(`Evidence: ${resolve(out,'browser-report.json')}`);}
